### ISSUE TITLE
this program suitable for non model organisn

### ISSUE THREAD

**Issue by ucbtsh6** [williamritchie/IRFinder#106]
Im dealing with non model organism its genome doesn't exists on ENsemble but I have GTF file with annotated exons only. can I use this program for analysis

**Comment by dg520** [comment]
Hi @ucbtsh6 ,

If you have the right FASTA and GTF pairs, you can apply IRFinder on non-model organisms. To find out what is a suitable customized GTF file, please read the manual [here](https://github.com/williamritchie/IRFinder/wiki/Build-Reference#using-customized-gtf). On the same page, it also includes instructions on how to build the reference using your local (customized) FASTA and GTF files.     
    
Best,
Dadi
