### ISSUE TITLE
integration with SIRFindeR

### ISSUE THREAD

**Issue by ojziff** [williamritchie/IRFinder#107]
Hi Dadi and others,

As per the new SIRFindeR tutorial I wondered if adding the equivalent filtering step for low coverage based on exonic & intronic abundances, would make the IRFinder IR ratios more stable e.g. `IRratio > 0 & SplicesMax > 100`

Many thanks,
Oliver

**Comment by dg520** [comment]
Hi @ojziff ,

I'm not familiar with S-IRFinderR, the latest IR tool developed by Dr. Ritchie's team, which I was not involved in. In general, increase cutoff for `spliceMax` in IRFinder will increase the stability of IR ratio measurement while will decrease the total number of IR detected in the sample. Please note, `spliceMax` in IRFinder is in "the number of reads" unit, meaning it is directly correlated to your RNASeq depth. If your overall sequencing depth is low, a high cutoff at 100 might end up with no IR detected.

Best,
Dadi
