### ISSUE TITLE
Attempting to reach alternatie build reference website, seems down 

### ISSUE THREAD

**Issue by sscho** [williamritchie/IRFinder#108]
I'm on the buildref part, and am attempting to get the hg38 build. I clicked on the link on the wiki build-reference page (https://github.com/williamritchie/IRFinder/wiki/Build-Reference) but it just hangs and stops. Is there a redundant site I can go into to get this build?

Additionally, I don't see the hg38 version of the following file: Human_hg19_wgEncodeDacMapabilityConsensusExcludable.bed.gz 

I tried omitting this option and it errors out saying "exclude.directional.bed is empty"

Thanks!

**Comment by dg520** [comment]
Hi @sscho ,

1. You've given IRFinder a wrong FTP address to build reference. You should use a command and FTP address like the following:
```
IRFinder -m BuildRef -r ReferenceDir ftp://ftp.ensembl.org/pub/release-XX/gtf/homo_sapiens/Homo_sapiens.GRCh38.XX.gtf.gz
```
You need to replace the two `XX` in the above command with the release version you want to use, For example, you can use `100` for the latest version.      
     
2. You can omit  `Human_hg19_wgEncodeDacMapabilityConsensusExcludable.bed.gz`. The error message you've seen is totally irrelevant to `Human_hg19_wgEncodeDacMapabilityConsensusExcludable.bed.gz`.      
    
Best,
Dadi
