### ISSUE TITLE
"Can't locate _mergesort.pm" when building reference

### ISSUE THREAD

**Issue by viktorfeketa** [williamritchie/IRFinder#112]
Building reference failed with the following error:
```
<Phase 3: IRFinder Reference Preparation>
Aug 25 18:14:05 ... building Ref 1...
Can't locate _mergesort.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/share/perl5/if.pm line 13.
BEGIN failed--compilation aborted at /gpfs/ycga/home/vf78/utils/IRFinder-1.3.1/bin/util/gtf2bed-custom.pl line 29.
```
If I change line 29 in gtf2bed_custom.pl from
`use if $]<5.028, sort, '_mergesort';`
to
`use if $]<5.028, "sort", '_mergesort';`
(add quotes around sort)
everything works.

Using IRFinder 1.3.1; Perl 5.28.
I am not sure if this error is my system-specific or general, but wanted to report and check that this doesn't alter the functionality of the program. Thank you.

**Comment by dg520** [comment]
Hi @viktorfeketa ,

You're definitely right. The quotes are needed. I've merged your suggestion to the master version. I'm also curious of how this error could be triggered on Perl 5.28. That's a bit of concern. 
Anyway, really appreciate your input!

Best,
Dadi

**Comment by viktorfeketa** [comment]
Actually, sorry, my bad, I was testing different Perl versions and got confused.
The error was getting triggered in Perl 5.16, was not triggered in 5.28, which makes total sense.
Otherwise, issue resolved! Thanks.

**Comment by dg520** [comment]
Hi @viktorfeketa ,
No problem! This makes sense now! 

Best,
Dadi
