### ISSUE TITLE
Is it possible to compare more than 2 groups of samples

### ISSUE THREAD

**Issue by qicaibiology** [williamritchie/IRFinder#114]
Hi:
Thanks for developing this tools and the generous help on using this tool.
I have a question on if it is possible to compare more than 2 groups of samples: eg, I have 4 stages of samples, each has 2 replicates. So far, I have compared each 2 combinations and merge the tables together. I am wondering if it is possible to feed all of them to the software at once and got a master table to filter?

Thank you very much?

Cai

**Comment by dg520** [comment]
Hi @qicaibiology ,
The short answer is: no, there is no module in IRFinder that is able to directly achieve what you want. 
But you can use the GLM-based approach to create all comparisons from all combinations and merge those tables manually. IRFinder's GLM uses DESeq2 kernel. You can consult DESeq2 manual to see how to do this.

Best,
Dadi

**Comment by qicaibiology** [comment]
Thank you for letting me know this.
