### ISSUE TITLE
Reference building error

### ISSUE THREAD

**Issue by edeneng** [williamritchie/IRFinder#115]
Hi,
I'm trying to build a reference for hg38 and encounter an error. 
I'm using IRFinder version 1.3.0 and got the genome and transcriptome files from Ensembl (with the FTP link). 
The STAR reference is built fine and the mapability step works ok as well, but it fails to complete the third step. 
**The log file shows this:**  

> <Phase 3: IRFinder Reference Preparation>
> Sep 15 16:10:22 ... building Ref 1...
> sort: unknown subpragma '_mergesort' at /cs/icore/eden.engal/IRFinder-1.3.0/bin/util/gtf2bed-custom.pl line 33.
> BEGIN failed--compilation aborted at /cs/icore/eden.engal/IRFinder-1.3.0/bin/util/gtf2bed-custom.pl line 33.
> Sep 15 16:10:22 ... building Ref 2...
> Sep 15 16:10:25 ... building Ref 3...
> Sep 15 16:10:25 ... building Ref 4...
> Sep 15 16:10:29 ... building Ref 5...
> Sep 15 16:10:34 ... building Ref 6...
> Sep 15 16:10:34 ... building Ref 7...
> Sep 15 16:10:34 ... building Ref 8...
> Sep 15 16:10:34 ... building Ref 9...
> Sep 15 16:10:34 ... building Ref 10c...
> Sep 15 16:10:34 ... building Ref 11c...
> Error: exclude.directional.bed is empty.
> Error: introns.unique.bed is empty.
> Error: ref-cover.bed is empty.
> Error: ref-read-continues.ref is empty.
> Error: ref-sj.ref is empty.
> Error: IRFinder reference building FAILED.

As it says, all the files in the IRFinder directory are empty. 
Do you know what could be the problem here and how can I figure this out? 

Thanks, 
Eden

**Comment by dg520** [comment]
Hi @edeneng ,

This is a known bug in IRFinder 1.3.0 when using Perl version < 5.28. It has been fixed in [IRFinder 1.3.1](https://github.com/williamritchie/IRFinder/releases/tag/v1.3.1). Could you please try that and re-run the reference preparation step?

Best,
Dadi

**Comment by edeneng** [comment]
It is working now with 1.3.1. 
Thank you!
