### ISSUE TITLE
Transcript ID for each retained intron

### ISSUE THREAD

**Issue by ojziff** [williamritchie/IRFinder#116]
Dear Dadi and IRFinder team,

I wondered if it was possible to allocate each IRFinder retained intron to a transcript ID?  It seems IRFinder utilises GTF transcript_biotype annotated "retained_introns" and excludes introns with overlapping GTF features. I know there may be >1 possible transcript ID for some retained introns, but it would be extremely helpful to know these for downstream analysis - e.g. comparing IR with transcript expression, examining IR transcript NMD probability... 

I have attempted to allocate a transcript ID using the following rather crude findOverlaps method and this still fails to allocate a transcript ID to many of the retained introns.
```
gtf.transcript <- gtf[ gtf$type %in% "transcript"] # filter ensembl GTF GRanges to only annotated transcripts
gtf.transcript.retained_intron <- gtf.transcript[ gtf.transcript$transcript_biotype %in% "retained_intron"] # filter to only annotated retained_introns
gr_IRFinder <- as.GenomicRange(IRFinder$Intron.GeneName.GeneID.Coords) # GRanges of IRFinder retained introns
gr_overlap <-  findOverlaps(query = gr_IRFinder, subject=gtf.transcript.retained_intron, ignore.strand=FALSE) # find overlaps between IRFinder retained introns and GTF retained intron transcripts
gtf.transcript.retained_intron.overlap <- unique(gtf.transcript.retained_intron[ queryHits(gr_overlap) ]) # subset to overlapping retained introns between GTF & IRFinder
IRFinder.transcriptID <- IRFinder %>% left_join(dplyr::select(as.data.frame(gtf_retained.introns.overlap.df), gene_name, Chr, "Direction" = "strand", "gene_id", transcript_id), by = c("gene_name", "Chr", "Direction", "gene_id")) # join transcript ID to IRFinder results
```

Many thanks for your help with this,
Oliver

**Comment by dg520** [comment]
Hi @ojziff ,

I'm not familiar with `findOverlaps`. As far as I see from your script above, I don't think you should filter for "retained_intron" in your second line. You should do directly overlap your transcript (from the first line) with your `gr_IRFinder`. You can do the "retained_intron" among your overlapped event and ask the question: how many of your detected IR events are annotated. 

IRFinder doesn't only look at IR for "retained_intron" in the GTF. It checks all the introns transcriptome-widely using RNASeq information. This is an unbiased approach. On the other hand, the "retained_intron" in the GTF is generated from limited resources and is evidence based. It's not a complete set, for example, it might refer to a set of tissues that are different than what you've sequence. 

Best,
Dadi
