### ISSUE TITLE
run error on conda installation

### ISSUE THREAD

**Issue by pillailab** [williamritchie/IRFinder#117]
Hello,
I ran a conda installation of irfinder to build the refernces and it worked fine. but when i run it for FastQ or BAM modes, it exits without any error message (the slurm message is empty). I am running it on a redhat compute cluster. I had installed all the dependencies in the conda environment.  Please advise
Thanks
Manoj

**Comment by dg520** [comment]
Hi @pillailab ,

The conda repository is automatically generated by the third-party. Could you please `git clone` the master directly from GitHub and try again? If the problem persisted, let me know, with your detailed information of your system, dependencies, standard error output on your screen for both reference preparation and quantification steps.

Best,
Dadi

**Comment by pillailab** [comment]
Thank you Dadi, so I installed from git and ran again and it gave error "GLIBCXX not found" and hence I followed your suggestion to make clean and make, but it again errored out. I am pasting the output of both of them below:

(base) [mp758@farnam2 irfinder]$ make clean
rm -f *.o irfinder Depend.list
(base) [mp758@farnam2 irfinder]$ make
/bin/rm -f ./Depend.list
g++ -pipe -std=c++0x -O3    -Wall -Wextra -fopenmp -D'COMPILATION_TIME_PLACE="Wed Sep 16 23:40:47 EDT 2020 farnam2.farnam.hpc.yale.internal:/home/mp758/project/Tools/IRfinder/IRFinder-1.3.0/src/irfinder"'   -MM ReadBlockProcessor.cpp FragmentBlocks.cpp IRFinder.cpp crc32.cpp ReadBlockProcessor_OutputBAM.cpp CoverageBlock.cpp ReadBlockProcessor_CoverageBlocks.cpp BAM2blocks.cpp >> Depend.list
g++ -c -pipe -std=c++0x -O3    -Wall -Wextra -fopenmp -D'COMPILATION_TIME_PLACE="Wed Sep 16 23:40:47 EDT 2020 farnam2.farnam.hpc.yale.internal:/home/mp758/project/Tools/IRfinder/IRFinder-1.3.0/src/irfinder"'   FragmentBlocks.cpp
g++ -c -pipe -std=c++0x -O3    -Wall -Wextra -fopenmp -D'COMPILATION_TIME_PLACE="Wed Sep 16 23:40:47 EDT 2020 farnam2.farnam.hpc.yale.internal:/home/mp758/project/Tools/IRfinder/IRFinder-1.3.0/src/irfinder"'   ReadBlockProcessor.cpp
g++ -c -pipe -std=c++0x -O3    -Wall -Wextra -fopenmp -D'COMPILATION_TIME_PLACE="Wed Sep 16 23:40:47 EDT 2020 farnam2.farnam.hpc.yale.internal:/home/mp758/project/Tools/IRfinder/IRFinder-1.3.0/src/irfinder"'   CoverageBlock.cpp
g++ -c -pipe -std=c++0x -O3    -Wall -Wextra -fopenmp -D'COMPILATION_TIME_PLACE="Wed Sep 16 23:40:47 EDT 2020 farnam2.farnam.hpc.yale.internal:/home/mp758/project/Tools/IRfinder/IRFinder-1.3.0/src/irfinder"'   ReadBlockProcessor_CoverageBlocks.cpp
g++ -c -pipe -std=c++0x -O3    -Wall -Wextra -fopenmp -D'COMPILATION_TIME_PLACE="Wed Sep 16 23:40:47 EDT 2020 farnam2.farnam.hpc.yale.internal:/home/mp758/project/Tools/IRfinder/IRFinder-1.3.0/src/irfinder"'   ReadBlockProcessor_OutputBAM.cpp
ReadBlockProcessor_OutputBAM.cpp:184:6: warning: unused parameter ‘chrmap’ [-Wunused-parameter]
 void OutputBAM::ChrMapUpdate(const std::vector<string> &chrmap) {
      ^
g++ -c -pipe -std=c++0x -O3    -Wall -Wextra -fopenmp -D'COMPILATION_TIME_PLACE="Wed Sep 16 23:40:47 EDT 2020 farnam2.farnam.hpc.yale.internal:/home/mp758/project/Tools/IRfinder/IRFinder-1.3.0/src/irfinder"'   BAM2blocks.cpp
g++ -c -pipe -std=c++0x -O3    -Wall -Wextra -fopenmp -D'COMPILATION_TIME_PLACE="Wed Sep 16 23:40:47 EDT 2020 farnam2.farnam.hpc.yale.internal:/home/mp758/project/Tools/IRfinder/IRFinder-1.3.0/src/irfinder"'   IRFinder.cpp
g++ -c -pipe -std=c++0x -O3    -Wall -Wextra -fopenmp -D'COMPILATION_TIME_PLACE="Wed Sep 16 23:40:47 EDT 2020 farnam2.farnam.hpc.yale.internal:/home/mp758/project/Tools/IRfinder/IRFinder-1.3.0/src/irfinder"'   crc32.cpp
g++ -o irfinder -pipe -std=c++0x -O3    -Wall -Wextra -fopenmp -D'COMPILATION_TIME_PLACE="Wed Sep 16 23:40:47 EDT 2020 farnam2.farnam.hpc.yale.internal:/home/mp758/project/Tools/IRfinder/IRFinder-1.3.0/src/irfinder"'   FragmentBlocks.o ReadBlockProcessor.o CoverageBlock.o ReadBlockProcessor_CoverageBlocks.o ReadBlockProcessor_OutputBAM.o BAM2blocks.o IRFinder.o crc32.o -static -static-libgcc
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
make: *** [Makefile:41: IRFinderStatic] Error 1

**Comment by dg520** [comment]
Hi @pillailab ,

Seems your system doesn't meet the minimal requirement to run IRFinder. Specifically, your OS doesn't include a proper C++ kernal for IRFinder. I can double confirm this for you if you sent me your OS version, GCC version and GLIBC version. But there is little I can help beyond that. I'm sorry. 

Best,
Dadi

**Comment by pillailab** [comment]
Hi Dadi,
Thank you for working with me on this - much appreciated.
versions of installations are as follows:
The compute cluster :
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"

The environment running IRFinder:
bedtools                  2.29.2               hc088bd4_0    bioconda
binutils_impl_linux-64    2.33.1               he6710b0_7    anaconda
binutils_linux-64         2.33.1              h9595d00_15    anaconda
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2020.7.22                     0    anaconda
curl                      7.69.1               hbc83047_0  
gcc_impl_linux-64         7.3.0                habb00fd_1  
gcc_linux-64              7.3.0               h553295d_15    anaconda
glibc                     2.19                          0    asmeurer
htslib                    1.9                  h4da6232_3    bioconda
krb5                      1.17.1               h173b8e3_0  
ld_impl_linux-64          2.33.1               h53a641e_7    anaconda
libcurl                   7.69.1               h20c2e04_0  
libdeflate                1.2                  h516909a_1    bioconda
libedit                   3.1.20181209         hc058e9b_0  
libgcc-ng                 9.1.0                hdf63c60_0  
libssh2                   1.9.0                h1ba5d50_1  
libstdcxx-ng              9.1.0                hdf63c60_0  
ncurses                   6.1                  he6710b0_1  
openssl                   1.1.1g               h7b6447c_0    anaconda
perl                      5.26.2               h14c3975_0  
samtools                  1.9                 h10a08f8_12    bioconda
star                      2.7.5c                        0    bioconda
tk                        8.6.10               hbc83047_0  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  

Best,
Manoj

**Comment by dg520** [comment]
Hi @pillailab ,

Here are my two cents:
1. I did a bit search for your OS. As shown [here](https://access.redhat.com/discussions/1182083?tour=8), `libstdc++` seems not to be included in the Red Hat system. You need to install it yourself, if you're the system admin. Or ask your admin to do that for you.
2.  I saw you have Anaconda versions of GCC and GLIBC. If you run `which gcc` and `gcc --version` in your terminal, does it point to your Anaconda GCC or is it the gcc comes with the OS? If the latter, you might want to try to use the Anaconda GCC to compile IRFinder. Not sure if that works, because it depends on whether that Anaconda GCC has been set with proper GLIBC and libstdc++. 

See which approach works for you. This issue involves root system setup, I'm sorry my suggestion is limited here. 

Best,
Dadi

**Comment by pillailab** [comment]
I had our administrator install it as a module and it is working correctly - they were unable to use the conda module. Thanks  for all the help 
Manoj
