### ISSUE TITLE
Uneven number of replicates

### ISSUE THREAD

**Issue by bounlu** [williamritchie/IRFinder#119]
Does IRFinder accept uneven number of replicates? e.g. 2 KD vs 1 Scr sample?

**Comment by dg520** [comment]
Hi @bounlu ,

If one condition contained only one sample while the other condition contained multiple samples, IRFinder does not support such comparison by default. That said, you can still do the comparison manually, by merging the condition with multiple samples in to one sample and then follow [this approach](https://github.com/williamritchie/IRFinder/wiki/No-Replicates-via-Audic-and-Claverie-Test) 

If you had uneven numbers where one condition contained >=3 sample while the other condition contained >=2 samples, you can use [this approach](https://github.com/williamritchie/IRFinder/wiki/Generalized-Linear-Model-with-Replicates)

Best,
Dadi
