### ISSUE TITLE
FATAL error with "analysisWithNoReplicates.pl"

### ISSUE THREAD

**Issue by bounlu** [williamritchie/IRFinder#121]
When running `analysisWithNoReplicates.pl` on the IRFinder output, I get the below error:

`FATAL: Files do not list records in the same order with identical number of lines.`

What could be the problem and how to fix?
Thanks.

**Comment by dg520** [comment]
Hi @bounlu ,

Can you check your files `IRFinder-IR-nondir.txt` or `IRFinder-IR-dir.txt` for each sample? Do they have the same number of lines? 

Best,
Dadi

**Comment by bounlu** [comment]
@dg520 

Thanks for reply.

Yes, indeed they have:

```
$ wc -l out/TCGA-DD-A11B/*/*dir.txt
  229694 out/TCGA-DD-A11B/1536f747-5f6f-4cba-97d1-f2eff32ab4af/IRFinder-IR-nondir.txt
  229694 out/TCGA-DD-A11B/4fdc7dba-5378-4695-8463-9812b8948868/IRFinder-IR-nondir.txt
```

**Comment by dg520** [comment]
@bounlu How did you run analysisWithNoReplicates.pl?

**Comment by bounlu** [comment]
Here is my full script:

```
#!/bin/bash

data_dir="/media/IRFinder/TCGA_LIHC"
analysis="/software/anaconda2/opt/irfinder-1.3.1/bin/analysisWithNoReplicates.pl"

while read -r line; do
	name=$(echo $line | cut -d " " -f1) && \
	file1=$(echo $line | cut -d " " -f2) && \
	file2=$(echo $line | cut -d " " -f3) && \

	mkdir -p "$data_dir/out/$name" && \

	sorted_bam_N="$data_dir/bam/$file1/Aligned.sortedByCoord.out.bam" && \
	unsorted_bam_N="$data_dir/bam/$file1/$name.N.unsorted.bam" && \
	samtools sort -n -@ 30 -m 4G "$sorted_bam_N" -o "$unsorted_bam_N" && \

	sorted_bam_T="$data_dir/bam/$file2/Aligned.sortedByCoord.out.bam" && \
	unsorted_bam_T="$data_dir/bam/$file2/$name.T.unsorted.bam" && \
	samtools sort -n -@ 30 -m 4G "$sorted_bam_T" -o "$unsorted_bam_T" && \

	read_length_N=`samtools view "$sorted_bam_N" | head -1000 | cut -f10 | awk '{print length}' | sort -nr | head -1` && \
	read_length_T=`samtools view "$sorted_bam_T" | head -1000 | cut -f10 | awk '{print length}' | sort -nr | head -1` && \

	IRFinder -m BAM -r "$data_dir/ref_hg19_$read_length_N" -d "$data_dir/out/$name/$file1" "$unsorted_bam_N" && \
	IRFinder -m BAM -r "$data_dir/ref_hg19_$read_length_T" -d "$data_dir/out/$name/$file2" "$unsorted_bam_T" && \
	
	"$analysis" -A "$data_dir/out/$name/$file2/IRFinder-IR-nondir.txt" -B "$data_dir/out/$name/$file1/IRFinder-IR-nondir.txt" > "$data_dir/$name.txt" || \

	echo "$name error" >> "$data_dir/done" && \
	echo "$name done" >> "$data_dir/done"
done < "$data_dir/tcga_lihc_50_pairs.txt"
```

**Comment by dg520** [comment]
@bounlu I cannot reproduce this error. Have you ever directly run
```
IRFinder/bin/analysisWithNoReplicates.pl \
-A out/TCGA-DD-A11B/1536f747-5f6f-4cba-97d1-f2eff32ab4af/IRFinder-IR-nondir.txt  \
-B out/TCGA-DD-A11B/4fdc7dba-5378-4695-8463-9812b8948868/IRFinder-IR-nondir.txt  \
> test_diffIR.txt
```
Does that give you the same error?

**Comment by bounlu** [comment]
@dg520 

Yes it still gives the same error but I think I found out the reason:

The two samples have different read lengths and the STAR library was constructed separately based on the read length.
ref_hg19_50 for tumor and ref_hg19_48 for the normal or vice versa. I use the corresponding library for each sample in the above code.

To make it work, I can obviously run both samples against the same library, but now the question is why IRFinder does not support this?
Is it a bug in the code or does it not make sense biologically to compare samples from different read lengths?

**Comment by dg520** [comment]
@bounlu 
IRFinder is designed to compare two samples from the same IRFinder reference for two reasons:
1. The order of intron in the two files must be the same. So Line 1 in file A will be compared to Line 1 in file B and so on. IRFinder checks this by investigating whether the same line from condition A and B have the same values in the first six columns.
2. The assumption behind Audic and Claverie Test is that the effective length of an intron in condition A and B must be the same. IRFinder checks this by investigating whether the same line from condition A and B have the same value at the 7th column. 

If your STAR reference is generated differently, it's very likely to disrupt the second rule even if you used the same GTF to generate those STAR references. You can manually check this by:
```
diff <(cut -f 1-7 out/TCGA-DD-A11B/1536f747-5f6f-4cba-97d1-f2eff32ab4af/IRFinder-IR-nondir.txt) <(cut -f 1-7 out/TCGA-DD-A11B/4fdc7dba-5378-4695-8463-9812b8948868/IRFinder-IR-nondir.txt)
```

It is not a bug. Instead, it's like this by purpose.

**Comment by bounlu** [comment]
@dg520 

Great, thanks a lot for the quick help and explanation!
