### ISSUE TITLE
understanding the IR differential analysis

### ISSUE THREAD

**Issue by ucbtsh6** [williamritchie/IRFinder#122]
Hello 
I want know to double check something is the result I get from
res.diff = results(dds, contrast=list("Condition_ko_vs_wt","Conditionwt.IRFinderIR"))  
the log fold change in this data is represent the change between the IR from the ko vs the wt???
so I want to see correlation between the proteome and the IR could I correlate the logfoldchange of this data 

with the difference between logfoldchange(RNA level) -logfoldchange(protein level)?

**Comment by dg520** [comment]
Hi @ucbtsh6 ,
In the tutorial, the log2 fold change in `res.diff ` represents the log2-transformed fold change of IR ratio between KO and WT. But your command to generate `res.diff` is wrong. You should use the one in the tutorial.
```
res.diff = results(dds, contrast=list("ConditionKO.IRFinderIR","ConditionWT.IRFinderIR"))  
```
The following lines in R will give you the correlation between log2 fold change of protein level and the log2 fold change of IR. But I don't know if this is what you want. You have to ask yourself.
```
#Assuming you have pre-calculated the log2 fold change of protein level as protein_LFC
cor(res.diff$log2FoldChange, protein_LFC)
```

Best,
Dadi
