### ISSUE TITLE
IRFinder output: Quantify IR vs Differential IR

### ISSUE THREAD

**Issue by ojziff** [williamritchie/IRFinder#123]
Dear @dg520,

I am comparing the outputs from [Quantify IR](https://github.com/williamritchie/IRFinder/wiki/Quantify-IR) and [Differential IR](https://github.com/williamritchie/IRFinder/wiki/Differential-IR-Analysis) and wondered why so many intron events are lost in the `Differential IR` output - `Differential IR` output only reports ~ 5% of the introns in the `Quantify IR` output. I am correlating IR with gene and protein levels but loose many events with the `Differential IR` output, resulting in weaker correlations.

Is it recommended to compare absolute levels of IR (IR ratio) in `Quantify IR` output between different groups, using IR ratio of 0.1 as the threshold to define a retained intron? It seems this was the approach used by [Green et al](https://pubmed.ncbi.nlm.nih.gov/32449925/) when comparing resting vs activated macrophages?

As always, many thanks for all your help with this,
Oliver

**Comment by dg520** [comment]
@ojziff , which Differential IR method do you refer to here? Clever and Audic or GLM? 
The GLM approach in the tutorial implements no pre-filtering step and should report all the IR events in the differential IR result.
The Clever and Audic approach does contain pre-filtering to get rid of low-confident IR events. The cutoffs are hard-coded. You can ban the pre-filtering steps by manually changing the source code:
In `analysisWithNoReplicates.pl`, you can change Line 171 from:
```
my $ok = ($pA[20] eq "-" || $pB[20] eq "-") && ($pA[8] >= 1 || $pB[8] >= 1) && (max($pA[16],$pA[17]) >= 10 || max($pB[16],$pB[17]) >= 10) && ($pA[19] >= 0.01 || $pB[19] >= 0.01);
```
to
```
my $ok = 1;
```

Or in `analysisWithLowReplicates.pl`, you can change Line 179 from:
```
my $ok = ($pA[20] eq "-" || $pB[20] eq "-") && ($pA[8] >= 1 || $pB[8] >= 1) && ($pA[19] >= 0.01 || $pB[19] >= 0.01) && separatedAB(\@repsIR, $repsA, $repsB);
```
to
```
my $ok = separatedAB(\@repsIR, $repsA, $repsB);
```

Be aware:  Although I kind of agree that using hard-coded cutoffs might not be a good practice, I still recommend filtering steps to control for false positives. They include but not limited to minimal intron coverage, minimal IR level, minimal correct splicing, etc. The suitable cutoffs should be selected based on the statistics/QC of your RNASeq libraries.    

For the paper from Green et al., please contact the corresponding author directly.

**Comment by ojziff** [comment]
That is very helpful, thank you @dg520 !

Yes i was using the analysisWithLowReplicates.pl script as i have 2 replicates for each condition. Removing this prefiltering step helped to restore many IR events (from 5% to 25%) but I am still missing ~75% of introns reported in `Quantify IR`.  I cant work out what the remaining prefiltering is - many of the filtered 75% have no Warnings in either condition i.e. `-` . Is this coming from line 185 in analysisWithLowReplicates.pl:

`## Check if both are sufficiently expressed (either the intron, or the splices)
    if (( $pA[8] >= 1 || max($pA[16],$pA[17]) >= 10 ) && ( $pB[8] >= 1 || max($pB[16],$pB[17]) >= 10 ))`

Many thanks,
Oliver

**Comment by dg520** [comment]
@ojziff No, Line 185 does not determine what to output. It judges whether the entry should go to Audic test or it should skip the test with an arbitrary value of 33 indicating only one condition has that IR detectable.

You can try to change Line 179 to `my $ok = 1;` and re-run. This might nor might not lead to an error. If the error did not occur, you should get the output for all introns as you want. If the error did occur, it would mean some entries did not fit the assumption of Audic test and should be skipped. 

BUT PLEASE NOTE: if IRFinder skipped some IR events in the result or give them an arbitrary value >1, it means they are not test-able and you should avoid using them in your correlation.
