### ISSUE TITLE
IRFinder does not produce directional output in BAM mode

### ISSUE THREAD

**Issue by koustav-pal** [williamritchie/IRFinder#125]
Hi, 

I am running IRFinder in BAM mode using my own annotation file which I have appropriately filtered for regions of interest. 

The steps leading up to the BAM file are:
- Adapter trimming and Alignment with STAR
- Merging of technical replicates
- Filtering for uniquely mapping read pairs
- Fixing mate information 
- Sorting by coordinate
- Removal of duplicates 
- Sorting once again by name

This file is then passed on to IRFinder. However, no directional output is produced. Another colleague of mine has processed the same file through IRFinder in FASTQ mode and has received a directional output. 

Can you please provide some direction as to what might be the problem?

**Comment by dg520** [comment]
@koustav-pal From your description, I guess you're talking about paired-end (PE) libraries. 
1. I don't know how you filtered for uniquely mapped reads. For example, if one read in a pair is uniquely mapped but the other pair is not, did you discard both reads? 
2. I've never applied mate information fixation on RNASeq. For DNA-seq (e.g. ChIPSeq, WGS, etc) this is fine, but I don't know why you need this step for your expression profile investigation. This step might generate unexpected order of reads in your final BAM file.
3. Although removing duplicates is unnecessary for RNASeq and would lead to underestimation of gene expression, you can leave the step there for your specific reasons. But again, if one read in a pair is duplicated but the other pair is not, you should remove both pairs.
4. You also need to make sure, although unlikely to happen, there is no duplicated read name across your technical replicates.
5. You can always double-check after you get your final BAM that whether (a) every two lines represent the same read pair; (b) every read pair is only represented by two lines in the BAM; (c) From every two lines, the first line should always represent Read1 while the second line should always represent Read2.

**Comment by koustav-pal** [comment]
Hi @dg520,
1. Yes, the condition is that reads must be mapped in a proper pair. For that example, the entire pair will be removed. 
2. I am using samtools markdup to remove duplicates. markdup requires that mate information be fixed prior to duplicate marking or removal.
3. I have also tried to run IRFinder without duplicate removal with the same result. No directional files were generated. 
4. There isn't. I use the same STAR parameters as outlined in the IRFInder manual. 
5. Since the file has passed through name sorting, this is indeed the case.

**Comment by dg520** [comment]
@koustav-pal Got you. If the BAM file is generated successfully in the right structure. Then let's look at the exact junction alignment information. Could you please paste here all the lines starting with "Directionality: " in the file `irfinder.stdout`? Thanks.

**Comment by koustav-pal** [comment]
Hi @dg520 

Directionality: Dir evidence:   96906
Directionality: Nondir evidence:        22737
Directionality: Dir evidence known junctions:   86525
Directionality: Nondir evidence known junctions:        19028
Directionality: Dir matches ref:        86525
Directionality: Dir opposed to ref:     0
Directionality: Dir score all (0-10000):        8099
Directionality: Dir score known junctions (0-10000):    8197

**Comment by dg520** [comment]
@koustav-pal Interesting. Among all the reads mapped to a junction-containing region, ~20% (i.e. 22737/(22737+96906) ) of them mapped to the opposite strand of that junction. IRFinder considers directional if this value is <= 10%. Empirically, this value should be as low as 1-2% in a high-quality directional library. You mentioned your colleague worked in FASTQ mode and got directional, I'm wondering how this metric looks like in your colleague's result. 

Are you using exactly the same GFF3 file? Has he/she merged technical replicates at FASTQ level before feeding to IRFinder?

It is worth to consider:
1. whether some of the replicates failed the directionality
2. if the annotation of known splice junctions is imperfect in GFF3
3. if there exist steps in the BAM processing leads to the bias which we haven't realized

You might want to check the alignment at junctions using a visualization tool such as IGV, and look closely at those read pairs assigned to the opposite strand of junctions. Check: 
1. whether the alignment is convincing
2. whether the annotation of junction strandness is correct (e.g. GT/AG is on the annotated strand)
3. if the alignments on the opposite strand are always from a specific replicate
4. if their Read1 and Read2 are correctly assigned according to the original FASTQ.

**Comment by koustav-pal** [comment]
Hi after a more detailed conversation with the aforementioned colleague I found out that also in FASTQ mode they do not get the directional files. Their starting annotation is different from mine. We looked into the directionality from RSeQC and found out that the library seems to be 80% RF stranded as opposed to FR stranded. What is even more interesting is that this pattern is same across all replicates and runs (~ 200 experiments). We are currently investigating the issue further. 

Can you please comment on how our analysis might be affected if we used the non-directional files?

**Comment by dg520** [comment]
@koustav-pal , The 80% RF observation from RSeQC is consistent with the estimation from IRFinder. IRFinder generates two versions of reference for directional and non-directional conditions respectively. They differ from each other in terms of how to deal with the overlapped introns and exons from two opposite strands. 

If a gene is NOT overlapped with another gene on its opposite strand, the directionality will NOT influence the IR estimation. In this case, introns are marked by `/clean` in the 4th column of the result file. The directionality only matters when two items overlapped. In this case, introns are marked by `/anti-near` or `/anti-clean` in the 4th column of the result file.
