### ISSUE TITLE
LowCoverage warnings across many RNA-seq datasets

### ISSUE THREAD

**Issue by glarue** [williamritchie/IRFinder#138]
I have a general analysis question, so pardon the somewhat involved setup here. I've run IRFinder on a non-model organism with a large number of scaffolds (you may recall this extreme—and very generous—troubleshooting from last year: #80). 

Though the STAR uniquely-mapped percentages are good (> 70% in all cases), for every RNA-seq sample used (~26 total, from a few different labs) there is a warning about low junction coverage in the `WARNINGS` output file. For comparison, here are CDFs of the junction-supporting read counts (from the `SJ.tab.out` file) for one sample in the non-model species (red) versus equivalent data in human (blue) where no warnings were produced:

![pp ERR557106 out tab junction_coverage_cdf 300](https://user-images.githubusercontent.com/6827531/109708344-23040c00-7b50-11eb-94d5-a58d6a309c15.png)

![total SRR10875528SJ out tab junction_coverage_cdf 300](https://user-images.githubusercontent.com/6827531/109708379-30b99180-7b50-11eb-86ba-44439f51e3d2.png)

If you look at the inset plots, you can see that in both cases a substantial fraction (~60-70%) of intron splice junctions are supported by < 10 reads, with the fraction a bit higher in the non-model case. One other thing I've noticed is that in the non-model genome, there are a few junctions with very high read counts (~150,000), but I don't have a good intuition for how surprising this should be. It also doesn't seem _that_ different from the human data (max per-junction read count ~30,000). The average number of reads per sample is ~30 million for the non-model species.

Considering all of this, my question is: do you have any suggestions for determining whether this is a problem with the underlying data (it has worked fine in other pipelines, e.g. annotation, etc.), or an issue somewhere else along the pipeline? I am concerned that something funny could have happened with the mapping, given the difficulty we had getting IRFinder to properly index the splice junctions to begin with, but am unsure where best to look to investigate further.

**Comment by dg520** [comment]
@glarue Great insight. This warning is expected for non-model organisms where the GTF annotation might be incomplete. This warning tells that there are too many bases in the RNASeq data not overlapping with ANNOTATED splicing junctions in the provided GTF. This threshold (i.e. frequency of a splice junction in the genome) is estimated from human GRCh37 and GRChm38.

Please note: 1) the `SJ.tab.out` from STAR records all junctions detected by the aligner, regardless they are annotated or not (BTW, there is a column in `SJ.tab.out` indicating novel-vs-annotated junction). 2) But IRFinder only works on annotation, because we have to know the start and end positions of each intron. 

I believe both STAR alignment and IRFinder work as their design in your case. I suggest first check `SJ.tab.out` to see whether it's dominated by novel junctions. If that's the case, there might be more unseen IR events by IRFinder due to annotation. If that's not the case, it might indicate your genome of interest has splice junctions less frequent (e.g. in every 1000bp) than that of human/mouse genome, which could be totally normal.

**Comment by glarue** [comment]
> @glarue Great insight. This warning is expected for non-model organisms where the GTF annotation might be incomplete. This warning tells that there are too many bases in the RNASeq data not overlapping with ANNOTATED splicing junctions in the provided GTF. This threshold (i.e. frequency of a splice junction in the genome) is estimated from human GRCh37 and GRChm38.

Very helpful, thank you for the quick response. Indeed, the annotation is only ~70% complete (per BUSCO), so it would be very surprising if there _weren't_ a significant number of junctions found outside of the annotated splice boundaries.

> I believe both STAR alignment and IRFinder work as their design in your case. I suggest first check `SJ.tab.out` to see whether it's dominated by novel junctions. If that's the case, there might be more unseen IR events by IRFinder due to annotation. If that's not the case, it might indicate your genome of interest has splice junctions less frequent (e.g. in every 1000bp) than that of human/mouse genome, which could be totally normal.

In this case, only ~30% of junctions are novel, which perhaps favors your second hypothesis. Does the junction frequency expectation account for average intron length? Is there a straightforward way to gauge the splice junction frequency (in the way IRFinder understands it) in the output data for the non-model species?

**Comment by dg520** [comment]
@glarue Junction frequency should be as plain as: 
```
F = number of bases annotated as splice junction / total number of bases of the genome 
``` 
In IRFinder's view, This F value is further corrected by average fragment length (Note: not read length) of the RNASeq library. That is:
```
corrected_F = F / (Fragment_length - 10)
```
We compare this `corrected_F` to 0.0008, the latter of which is estimated from human/mouse genome assuming a 75bp library.

**Comment by glarue** [comment]
> @glarue Junction frequency should be as plain as:
> 
> ```
> F = number of bases annotated as splice junction / total number of bases of the genome 
> ```
> 
> In IRFinder's view, This F value is further corrected by average fragment length (Note: not read length) of the RNASeq library. That is:
> 
> ```
> corrected_F = F / (Fragment_length - 10)
> ```
> 
> We compare this `corrected_F` to 0.0008, the latter of which is estimated from human/mouse genome assuming a 75bp library.
> 
> [UPDATE]
> For quick Fragment_length calculation used by IRFinder, you can refer to values in `irfinder.stdout`:
> 
> ```
> Fragment_length = Total nucleotides/(Total pairs processed + Total singles processed + Error reads)
> ```

I think I understand, but let me quickly clarify in the service of trying to quickly calculate some rough numbers to compare to my species of interest: when you say "number of bases annotated as splice junction", how would this be calculated for a given splice junction using, say, the IRFinder output or `SJ.tab.out`? The total range spanned by columns 2 and 3 in `SJ.tab.out`?

**Comment by dg520** [comment]
@glarue Sorry, the previous information was totally wrong. The frequency was calculated as:
```
F = Sum of depth at splice junction in RNASeq / sum of depth at any base in RNASeq 
corrected_F = F / (Fragment_length - 10)
```

**Comment by glarue** [comment]
> @glarue Sorry, the previous information was totally wrong. The frequency was calculated as:
> 
> ```
> F = Sum of depth at annotated splice junctions in RNASeq / sum of depth at any base in RNASeq 
> corrected_F = F / (Fragment_length - 10)
> ```

Sorry to belabor the point, but to concretize: how would `sum of depth at any base in RNASeq` from IRFinder/STAR output files?

I hope it goes without saying, but thank you very much for all your help with this.

**Comment by dg520** [comment]
@glarue No problem at all!
To get `Sum of depth at annotated splice junctions in RNASeq`, you can refer to `IRFinder-JuncCount.txt` and add up all values in Column 5, excluding those with "." (dot) in Column 4. 
To get `sum of depth at any base in RNASeq`, you can use `IRFinder-ChrCoverage.txt` and add up all values in Column 2, excluding values from mitochondria chrosome if there is any.

**Comment by glarue** [comment]
> @glarue No problem at all!
> To get `Sum of depth at annotated splice junctions in RNASeq`, you can refer to `IRFinder-JuncCount.txt` and add up all values in Column 5, excluding those with "." (dot) in Column 4.
> To get `sum of depth at any base in RNASeq`, you can use `IRFinder-ChrCoverage.txt` and add up all values in Column 2, excluding values from mitochondria chrosome if there is any.

Hmm, well, calculating the frequency for both the species of interest as well as my own sample for human, I've got the opposite of what we were thinking:

```
SOI frequency (corrected): 0.00229
human frequency (corrected): 0.00137
```

Comparing the SOI frequency to IRFinder's internal expectation as well as my own (single RNA-seq sample) human data, the frequency for the SOI is _higher_ than the others. I don't want to trouble you more than necessary, but if you have any further thoughts or insights here I'd be interested to hear. Thanks again.

**Comment by dg520** [comment]
@glarue The exact calculation is taken care by `bin/util/warnings`. We might need to run through it to see where the differentiated results come from. Let me know if you cannot achieve that from your end. I can directly look into your `IRFinder-ChrCoverage.txt`, `IRFinder-JuncCount.txt` and `irfinder.stdout` files.

**Comment by glarue** [comment]
Update: one part of the issue solved. `warnings` was not properly parsing the `IRFinder-JuncCount.txt` output due to the "chromosomes" being called `ScaffoldN` instead of `chrN` (or just `N`), such that `$sjKnownTotalBase` was set to 0 and therefore, the SJ frequency calculated by `warnings` was also 0.

In `/bin/util/warnings` line 91, there is a format check for chromosome names (see arrow):
```perl
open IF, '<', "$outDir/IRFinder-JuncCount.txt";
while(<IF>) {
    my ($chr, $start, $end, $dir, $c) = split /\t/;
    if ($chr =~ m/^(chr)?[0-9]/i) {   # <--- line 91
        if ($dir eq ".") {
            $sjUnknownTotalBase += $c;
            $sjUnknownCountBase += 1 if ($c > 0);
        }else{
            $sjKnownTotalBase += $c;
            $sjKnownCountBase += 1 if ($c > 0);
        }
    }
}
close IF;
```
Modifying my `JuncCount` file to remove the "Scaffold" prefix fixed the calculation and removed the warning about low splice junction representation. It now gives an error about unannotated junctions, but that is consistent with our discussion earlier about the incompleteness of the annotation.

Given all of that, I'm now just left with the fact that a large number of introns have a `LowCoverage` warning in the output data (e.g. the plots in my original post), but per your original response I am assuming this is not a great concern given the nature of the genome?

**Comment by dg520** [comment]
@glarue That makes sense. 
I didn't realize your true concern is the `LowCoverage` tag in the last column of your output file. That will be independent of what we've discussed so far. The `bin/util/warning` script is a transcriptome-wide summary (i.e. which might be influenced by the completeness of annotation) while the `LowCoverage` tag is per-intron specific. The `LowCoverage` means the absolute splice-out, measured by the number of reads spliced at the junctions, of the intron is low. That is not directly associated with intron length, but with gene/transcript expression instead.  One example of checking gene expression in human brain tissue. Brain-specific genes usually have long introns in average. But `LowCoverage` tag will not be assigned to them as they are highly expressed in the brain. 

To summarize what we've discussed:
1. "WARN: Very low portion of reads have a splice junction. This may indicate the experiment is not an mRNA-Seq experiment." is caused by IRFinder not recognizing the chromosome nomenclature of your genome. After correcting the code, we can rule out that your genome has sparse splice junction distribution.
2. "LowCoverage" suggests two flanking exons of the intron of your interest are spliced and connected at a low level. This might be due to:
    a) the overall expression of the host transcript is low. You can try to rank transcript expression (e.g. in TPM) from high to low and check whether "LowCoverage" tags happen more often in lowly ranked transcript; or
    b) your overall sequencing depth is low. If all transcripts contain a lot of "LowCoverage" tags, you might want to ask whether the sequencing depth is sufficient. How many uniquely mapped reads have you got? I hope it's at least 20M. If it's below this number, you might want to ignore "LowCoverage" tags in your analyses, as the cutoff might be too stringent for your library. This won't influence the IR calculation; or 
    c) The estimated library complexity is low, which could be caused by issues during library preparation.

**Comment by glarue** [comment]
> @glarue That makes sense.
> I didn't realize your true concern is the `LowCoverage` tag in the last column of your output file.

Apologies for not being clearer—my concern was both, but I mistakenly thought the transcriptome-wide warning was related to the intron-level warnings. Thank you very much for explaining.

> 2. "LowCoverage" suggests two flanking exons of the intron of your interest are spliced and connected at a low level. This might be due to:
>    a) the overall expression of the host transcript is low. You can try to rank transcript expression (e.g. in TPM) from high to low and check whether "LowCoverage" tags happen more often in lowly ranked transcript; or
>    b) your overall sequencing depth is low. If all transcripts contain a lot of "LowCoverage" tags, you might want to ask whether the sequencing depth is sufficient. How many uniquely mapped reads have you got? I hope it's at least 20M. If it's below this number, you might want to ignore "LowCoverage" tags in your analyses, as the cutoff might be too stringent for your library. This won't influence the IR calculation; or
>    c) The estimated library complexity is low, which could be caused by issues during library preparation.

Thanks for the overview—the average number of uniquely-mapped reads is ~30M in the SOI, so perhaps that's a bit on the low side? At any rate, given that there is no longer a general warning I believe I can evaluate the other factors as needed. Thanks again for your patient assistance.
