### ISSUE TITLE
Crash IRFinder with 0 informative base introns

### ISSUE THREAD

**Issue by dwishsan** [williamritchie/IRFinder#15]
Hi Dadi,

I wanted to use your tool to analyze all the introns of my Human hg19 genome. In order to do this, I changed the line 82 of IntronExclusion.pl to :
if ($newlen >= 0) {

The index creation works well, but when I try the IRFinder script on my data, I get the following error :
./IRFinder-IRFinder-1.2.0/bin/IRFinder: line 554: 20035 Broken pipe             gzip -cd "$1"
     20036 Aborted                 | "$LIBEXEC/irfinder" "$OUTPUTDIR" "$REF/IRFinder/ref-cover.bed" "$REF/IRFinder/ref-sj.ref" "$REF/IRFinder/ref-read-continues.ref" "$REF/IRFinder/ref-ROI.bed" "$OUTPUTDIR/unsorted.frag.bam" >> "$OUTPUTDIR/irfinder.stdout" 2>> "$OUTPUTDIR/irfinder.stderr"
ERROR: IRFinder appears not to have completed. It appears an unknown component crashed.
ERROR: IRFinder appears not to have completed. It appears an unknown component crashed.
ERROR: IRFinder appears not to have completed. It appears an unknown component crashed.

And, in the irfinder.stderr file : 
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoul

Is it possible to run such analysis with the current version of IRFinder ? If it is, do you have an idea about what could be the problem ?

Thanks !
Audric Cologne

**Comment by dg520** [comment]
Hi Audric,

IRFinder uses effective length (`newlen`) instead of true length to against the inflated estimation of IR due to those confounding factors. As expected, the value of `newlen` should be more than 1bp. Otherwise, in the following calculation errors occur.

If you really want to keep all introns in the annotation, the easiest way to create your own script using samtools/bedtools and the alignment result from STAR (otherwise you have to modify IRFinder reference file which is complicated and can be avoided).

Here is a piece of pseudo code:

````
for (each_intronic_region):
    distribution = samtools depth -a -r intron_coordinates STAR.out.bam 
    #This calculates the base-wised depth of a certain intron from BAM file
    #Use "-a" option to keep positions with 0 depth. This is important.
    distribution_sort = sort(distribution)
    #Sort the depth 
    valueA = average ( (middle 40% of distribution_sorted) )
    #Take the average of the middle 40% of the sorted depth
    #This value A is used as estimated intronic depth for this intron
    valueB =  number of reads spliced at the two intron boundaries
    #This value can be figure out in the 7th column in the SJ.out.tab file created by STAR alignment
    IR = valueA / (valueA + valueB)
    #This is IR ration for this intron
````

Best,
Dadi

**Comment by dwishsan** [comment]
Hi Dadi,

Thanks for your solution. The problem is I will use the intronic reads information while I know that there is no informative bases in this intron. That's why I would like to use reads overlapping the exon-intron junctions. 
But I guess I can use "samtools view" in order to count reads on both exon-intron and intron-exon junctions. 

I also tried to modify the IRFinder reference. For exeample, if I wanted to add this intron : 
chr11:1006618-1008011

I created those lines in ref-cover.bed : 
11	1006622	1008006	dir/ARTIFICALGENE93/ENSG93/+/1/1006617/1008011/1394/10/clean	0	+	1006622	1008006	255,0,0	1	1384	0
11	1006622	1008006	nd/ARTIFICALGENE93/ENSG93/+/1/1006617/1008011/1394/10/clean	0	+	1006622	1008006	255,0,0	1	1384	0

But, when I use the IRFinder script, I get this line : 
11	1006617	1008011	ARTIFICALGENE102/ENSG102/clean	0	+	10	1	7.24368	6	7	9	11	1008135	1009099	AP2A2/ENSG00000183020/known-exon+anti-near	0	+	157	1	4.27245	2	4	7	22	2	6.15	3.4	334	331	331	0.0126302	NonUniformIntronCover

The positions are the same, but the gene ID is different and it is merged with another line (starting at field 14). That's really weird, I still try to find out what's wrong with my modify ref-cover.bed file.

**Comment by dg520** [comment]
Hi Audric,

1. Reads overlapping the exon-intron junctions are recorded in the 8th and 9th column of `SJ.out.tab` generated by STAR.

2. One of the primary purpose of IRFinder is to estimate robust IR by considering effective length. If you really DO NOT want to use effective length, that's something other than IRFinder and that's much easier to be achieved outside IRFinder. 

3. IRFinder generates its reference in a series of steps. Directly integrating `ref-cover.bed` is likely to mess things up, except we're sure the integrated part doesn't conflict with other files (`ref-sj.ref` and `ref-read-continues.ref`). I should have not recommended that to users. But if for some reasons you really need IRFinder to finish this task, maybe let's try the following:
a) modify `newlen` cutoff to `>=0` in the script `IntronExclusion.pl`
b) still in `IntronExclusion.pl`, comment out the whole loop of `foreach my $overlap (@$overlaps)`. It is the core part to throw out "bad" introns.
c) prepare the IRFinder reference. At this stage, it should finish successfully. Zero effective length is allowed in the reference preparation stage but is not allowed during quantification. More importantly, this will create the corresponding record of your intron of interest in the ref-sj.ref` and `ref-read-continues.ref`.
d) now open `ref-cover.bed`. Check if your intron of interest is there. Pay attention to the last three columns in the line. 10th column should be `1`; 11th column should be a value of intron length or intron length minus 10; 12th column should be `0`. Also pay attention to the 4th column. The second last field of this column should be either `0` or `10`.  
e) If everything makes sense, try to run the quantification.

Haven't test this on my end so it might not work. Let me know, probably I have to re-think. However, my best suggestion is to do it outside IRFinder. It's much more easier and cleaner.

Best,
Dadi
