### ISSUE TITLE
Estimate Gene Expressions in Predicted IRs

### ISSUE THREAD

**Issue by cherlynty** [williamritchie/IRFinder#151]
Hi,

This is probably more of a question: Do you have any advise on ways to estimate gene expression within IRs predicted from IRFinder? Thanks.

Cherlyn

**Comment by dg520** [comment]
@cherlynty Do I understand correctly: You're looking at the IR ratio of Intron A and now you want to know the expression of the gene that hosts/contains this intron A? If so, you can estimate gene expression using tools such as `htseq-count`.

**Comment by cherlynty** [comment]
Hi Dadi,

  Thank you for your message. I am wondering if it's possible to determine the fraction of gene expression that is attributed from intron retention within Intron A, as such its not masked by other introns that are contained within the gene. Are they are possible ways to estimate the proportions? Thanks

**Comment by dg520** [comment]
@cherlynty Firstly, for most gene expression calculations in their default modes (e.g. `htseq-count`), intronic reads are not counted at all. In other words, gene expressio and IR are independent. Secondly, IRFinder measures IR in its own scale (i.e. not count-based), which cannot be compared to gene expression directly. 

To achieve what you want, you need to apply `bedtools intersect` on the BAM file and figure out how many reads there are within the gene and within in the intron respectively. And then calculate the proportion from there. But this proportion value should be interpreted differently than you might expect: it actually tells you the splicing efficiency of this specific intron during the transcription of the host gene. And the lower the proportion, the more efficient the transcription.

**Comment by cherlynty** [comment]
Thank you, my aim is to derive potential functions from specific IRs, and in a way deconvolve the contributions from each retained intron.  In this case, could you also advise me on possible ways in inferring/correlate gene expressions from transcripts with IR vs those without in a given gene?

**Comment by dg520** [comment]
@cherlynty Now you brought in a new concept: transcript expression. That is not something can be directly measured from short-read RNASeq. But there are methods based on maximum-likehood-estimation (MLE) algorithm can help you approximate that. You might want to have some reading of tools such as RSEM or Kallisto. Whatever you want to do after this point should be quite straightforward (as you have both transcript expression and IR estimated), although I didn't fully get what you aimed at.

**Comment by cherlynty** [comment]
@dg520 thanks for the insights. I think I am trying to associate IR events with gene expression. I am seeing IRs within different introns in given gene. Hence, I am trying to 1. determine how a transcript with IR would affect gene expression (comparing gene expressions in transcripts with IR vs those without) and 2. determine how a transcript with a specific IR (ie Intron A but not Intron B of a gene) influences changes in expression at the gene and protein level. Does that make sense?

**Comment by dg520** [comment]
@cherlynty Seems you're using transcript-expression and gene-expression interchangeably. They are related yet quite different. It is crucial to realize that gene expression is an overall estimation while it can be deconvolved into the expression of a set of defined transcript via MLE or other algorithm. In other words, gene and transcript are at two different levels. 

The IR ratio estimated by IRFinder is at gene-level. It makes sense to correlate these IR ratios with gene expression, but it doesn't make sense to correlate these IR ratios with transcript expression. To do the latter, you need to find a way to deconvolve IR ratios to transcript level first. Without this pre-processing, you cannot know exactly which transcript contains the IR of interest. Also note, there might be novel transcripts related to the IR of your interests.  

With that being said, I definitely know nothing about your project. I just think IRFinder is not the right tool to solve transcript-level questions.
