### ISSUE TITLE
problems generating reference

### ISSUE THREAD

**Issue by william-hamilton** [williamritchie/IRFinder#159]
Hi All,
I'm also having trouble building the reference.
I generated a STAR reference using a genome downloaded from USCS (mm10) and guided by gencode.vM27.annotation.gtf and then used this to generate the IRFinder with the command
 
IRFinder -m BuildRefFromSTARRef -r /home/whamilton/2c_like/mem_etal/IRFinder/REF3/ -x /home/whamilton/IRFinder_starGenome
which outputted this on completion
 
Launching reference build process. The full build might take hours.
<Phase 1: STAR Reference Preparation>
Mar 17 11:51:29 ... copying the genome FASTA file...
Mar 17 11:51:48 ... copying the transcriptome GTF file...
Mar 17 11:51:51 ... copying the STAR reference folder...
<Phase 2: Mapability Calculation>
Mar 17 11:52:52 ... mapping genome fragments back to genome...
Mar 17 15:59:10 ... sorting aligned genome fragments...
[bam_sort_core] merging from 100 files...
Mar 17 16:18:13 ... indexing aligned genome fragments...
Mar 17 16:21:13 ... filtering aligned genome fragments by chromosome/scaffold...
Mar 17 17:07:57 ... merging filtered genome fragments...
Mar 17 17:08:40 ... calculating regions for exclusion...
Mar 17 17:14:46 ... cleaning temporary files...
<Phase 3: IRFinder Reference Preparation>
Mar 17 17:14:46 ... building Ref 1...
Mar 17 17:15:20 ... building Ref 2...
Mar 17 17:15:24 ... building Ref 3...
Mar 17 17:15:24 ... building Ref 4...
Mar 17 17:15:52 ... building Ref 5...
Mar 17 17:16:27 ... building Ref 6...
Mar 17 17:16:28 ... building Ref 7...
Mar 17 17:16:31 ... building Ref 8...
Mar 17 17:16:32 ... building Ref 9...
Mar 17 17:16:32 ... building Ref 10c...
Mar 17 17:16:32 ... building Ref 11c...
however when I try analysing my RNA-seq using the command
 
IRFinder -m BAM -r /home/whamilton/2c_like/mem_etal/IRFinder/REF3 -d /home/whamilton/2c_like/mem_etal/IRFinder/test_results /home/whamilton/2c_like/mem_etal/IRFinder/bam/rna_dp_rep_2_Aligned.sortedByCoord.out.bam
 
I get this error
ERROR: IRFinder appears not to have completed. It appears an unknown component crashed.
ERROR: IRFinder appears not to have completed. It appears an unknown component crashed.
ERROR: IRFinder appears not to have completed. It appears an unknown component crashed.
 
I have tried this a few times, re making each reference, and remapping the bam but it always crashes.
the IRFinder directory generated  by BuildRefFromSTARRef looks like this
 
-rw-rw-r-- 1 whamilton whamilton 23715801 Mar 17 17:15 exclude.directional.bed
-rw-rw-r-- 1 whamilton whamilton 29283619 Mar 17 17:15 exclude.omnidirectional.bed
-rw-rw-r-- 1 whamilton whamilton        0 Mar 17 17:16 intergenic.ROI.bed
-rw-rw-r-- 1 whamilton whamilton 13030939 Mar 17 17:15 introns.unique.bed
-rw-rw-r-- 1 whamilton whamilton 84937578 Mar 17 17:16 ref-cover.bed
-rw-rw-r-- 1 whamilton whamilton  6373822 Mar 17 17:16 ref-read-continues.ref
-rw-rw-r-- 1 whamilton whamilton    39922 Mar 17 17:16 ref-ROI.bed
-rw-rw-r-- 1 whamilton whamilton  5814493 Mar 17 17:16 ref-sj.ref
 
where the intergenic.ROI.bed is always empty.
 
Do you have any idea where I could be going wrong because I have no idea where to troubleshoot from here?
 
Yours in thanks,
William

**Comment by dg520** [comment]
@william-hamilton Hi William, let's try to rescue the empty `intergenic.ROI.bed` first. 

Assume:
1. your IRFinder reference folder is at `XXX/IR_REF` 
2. your IRFinder program folder is at `XXX/IRFinder`
3. the GTF file location is `XXX/gencode.vM27.annotation.gtf`

First define the essential variables:
```
GTF=XXX/gencode.vM27.annotation.gtf
CHRLEN=XXX/IR_REF/STAR/chrNameLength.txt
```

Now change your working directory and run the following:
```
cd XXX/IR_REF/IRFinder
XXX/IRFinder/bin/util/gtf2bed-custom.pl "$GTF" | awk 'BEGIN {FS="\t"; OFS="\t"} ($10>1) {print $1,$2,$3,$4,$5,$6 }' > tmp.all.annotations
bedtools slop -b 10000 -g "$CHRLEN" -i tmp.all.annotations | sort -t $'\t' -S 500M -k1,1 -k2,2n -k3,3n > tmp.1 
bedtools merge -d 1000 -i tmp.1 | bedtools complement -i stdin -g <(sort -k1,1 "$CHRLEN") > tmp.2
cat tmp.2 | awk 'BEGIN {FS="\t"; OFS="\t"} (length($1)<=2) {$4 = "Intergenic/" $1; print $1, $2, $3, $4}' > intergenic.ROI.bed
```
Is `intergenic.ROI.bed` still empty? If not, please run `IRFinder -m BAM` again. If that error persists, there is issue in the `irfinder` core. You have to recompile it. Please consult this repository's Wiki page for how to do that.
If  `intergenic.ROI.bed` is still empty, is either `tmp.1` or `tmp.2` empty? 
If you encountered `bedtools` errors, you have to figure out why (e.g. probably a version issue ) and re-run the IRFinder reference preparation with the right `bedtools` setup.  

Let me know.

Best,
Dadi

**Comment by dg520** [comment]
@william-hamilton Another issue I just realized: you need to feed IRFinder with a NAME-SORTED BAM. Please see the wiki page how to use BAM mode.

**Comment by william-hamilton** [comment]
Hi Dadi, 
thanks so much for the quick response. I followed the instruction you outlined above, but tmp.all.annotations, tmp.1 , tmp.2 and intergenic.ROI.bed were all empty. I'm running bedtools/2.26
Thanks for again you help.
Best, 
William

**Comment by dg520** [comment]
@william-hamilton 
Hi William,
An empty `tmp.all.annotations` is super-weird, meaning either your Perl or the GTF has something wrong, although I think it's highly unlikely. 
Nevertheless, `intergenic.ROI.bed` should not prevent you from running quantification. Can you try to re-run `IRFinder -m BAM` with a name-sorted BAM? Let's see if the quantification works when giving the right BAM and then we can come back to look deeper into your empty `intergenic.ROI.bed` problem.

Best,
Dadi

**Comment by william-hamilton** [comment]
Hi Dadi, 
Initially I mapped everything to UCSC mm2, and I had read some places that there were often issues with chromosome names in the bam bam files (chr 1 vs 1 etc.), So I downloaded both the genome and annotations from Ensembl, remade the STAR reference and the IRFinder reference builds normally (intergenic.ROI.bed is outputted). I remapped the fastq with ` --outSAMtype BAM Unsorted ` but BAM mode still crashes. I get the error

`/config/binaries/irfinder/1.3.1/bin/util/irfinder: /lib64/libstdc++.so.6: version GLIBCXX_3.4.20 not found (required by /config/binaries
/irfinder/1.3.1/bin/util/irfinder)`


I guess this is something the sys admin need to resolve?
Thanks again for all your help with this, 
Best, 
William

**Comment by dg520** [comment]
@william-hamilton 
Hi William,
Yes, the error means you need to recompile irfinder core. If your GCC >= 4.9.0, you can try to do it yourself according to the instruction [here](https://github.com/williamritchie/IRFinder/wiki/Download-and-Install#compilation-optional). 
If you cannot compile it successfully, please contact your sys admin for help. 

Alternative options to install IRFinder v1.3.1 include: 
1) using its Docker [image](https://hub.docker.com/r/dg520/bulkrnaseq), if your system supports Docker and you know its basic operations;
2) trying its anaconda [package](https://anaconda.org/bioconda/irfinder), although this package is prepared by a third-party.

Best,
Dadi
