### ISSUE TITLE
IRFinder used on other species?

### ISSUE THREAD

**Issue by duchen-whu** [williamritchie/IRFinder#163]
Hi, I want to use IRFinder to quantify IRratio through drosophila RNA-seq, but when I built index from local STAR reference, it reported errors, like following: 
Error: exclude.directional.bed is empty.
Error: introns.unique.bed is empty.
Error: ref-cover.bed is empty.
Error: ref-read-continues.ref is empty.
Error: ref-sj.ref is empty.
Error: IRFinder reference building FAILED.

I want to know if IRFinder can be used on other species, and any format requirements for gtf or nonPolyA.bed file?
Thanks!

**Comment by dg520** [comment]
@duchen-whu 
Firstly, make sure the GTF and the FASTA for reference building have the same chromosome nomenclature. For example. they both have to be "1, 2, 3...". Alternatively, both have to be "chr1, chr2, chr3..."

Then for each `exon` entry in your GTF, the last column must contain a tag of `transcript_biotype`. 

Finally, in at least some of these `exon` entries, the value for `transcript_biotype` tag must be either `"protein_coding"` or `"processed_transcript"` (with quotes). If none `exon` entry had these values, it would lead to an error as you saw.

**Comment by duchen-whu** [comment]
Thanks for your reply!
I have solved this problem already by changing the gtf format.
