### ISSUE TITLE
Differential IR Analysis output

### ISSUE THREAD

**Issue by rohbs** [williamritchie/IRFinder#165]
Hi, just a quick question on the differential IR analysis output (no more than 2 replicates): in the comparison script example if A is "treated or KO" and B is "control or WT" samples, is the output showing KOvsWT or WTvsKO? so for example, if p-diff=p-increased, does this mean there is increased intron retention (IRratio) in the treated sample (A) or in the WT (B) sample?
thanks!

**Comment by dg520** [comment]
@rohbs You can double check whichever condition has a higher IR by checking and comparing the "A-IRratio" and "B-IRratio" columns. `p-diff` always reports the minimum between `p-increased` and `p-decreased`.
