### ISSUE TITLE
IR-FINDER-S

### ISSUE THREAD

**Issue by adi8897** [williamritchie/IRFinder#182]
hi im trying to use it via singularity. i did the firs step of Quantify IR
i think something is not working well but i can not put the finger on the reason i would like for you're help please:
this is the command i ran, the data is a very reliable data. the bam files was created well.

i ran this command
singularity run --bind /sci/labs/maayan.salton/adi8897:/data /sci/labs/maayan.salton/adi8897/master_project/IRFinder.sif BAM -r /data/IR_finder_venv/IRFinder-2.0-beta/REF/Human-GRCh38-release110 -d /data/master_project/SART3/irfinder/SRR21796788 /data/master_project/SART3/row_data/bam_files/sorted_files/SRR21796788_Aligned.out_sorted.bam

the error logfile did not say anything but: please look at this file it does not look well
i would like your help to understand it- there is alote of event but only a few w
[IRFinder-IR-nondir.txt](https://github.com/williamritchie/IRFinder/files/14547159/IRFinder-IR-nondir.txt)
ith a normal p value, when running in the previous version it was not like this

**Comment by dg520** [comment]
@adi8897 You are on a wrong site.    
This site maintains the original IRFinder, not IRFinder-S. IRFinder-S is developed by another group and I have no clue how it works. Please consult their developers on [this site](https://github.com/RitchieLabIGH/IRFinder) for your questions.     
I will close this thread for now.
