### ISSUE TITLE
ref-cover.bed missing

### ISSUE THREAD

**Issue by OSchwich** [williamritchie/IRFinder#19]
Dear all, 

I am currently establishing IRFinder 1.2.0 in our lab.
I ran the Ref-Building process using our own FASTA and gtf-file and in addition ran the suggested pipeline via the ensembl-FTP. 
In both cases the building process seemed to work.
 
/home/Apps/IRFinder/bin/IRFinder -m BuildRef \
-r /home/Apps/IRFinder/REF/Mouse-mm10-release81 \
-S /home/Apps/STAR-2.5.2b/bin//Linux_x86_64/STAR \
-e /home/Apps/IRFinder/REF/extra-input-files/RNA.SpikeIn.ERCC.fasta.gz \
-R /home/Apps/IRFinder/REF/extra-input-files/Mouse_mm10_nonPolyA_ROI.bed \
ftp://ftp.ensembl.org/pub/release-81/gtf/mus_musculus/Mus_musculus.GRCm38.81.gtf.gz

2017-07-27 09:32:30 (2.74 MB/s) - 'Mus_musculus.GRCm38.81.gtf.gz' saved [277875$

Jul 27 09:33:41 ..... started STAR run
Jul 27 09:33:41 ... starting to generate Genome files
Jul 27 09:35:01 ... starting to sort Suffix Array. This may take a long time...
Jul 27 09:35:20 ... sorting Suffix Array chunks and saving them to disk...
Jul 27 09:57:32 ... loading chunks from disk, packing SA...
Jul 27 10:05:56 ... finished generating suffix array
Jul 27 10:05:56 ... generating Suffix Array index
Jul 27 10:09:25 ... completed Suffix Array index
Jul 27 10:09:25 ..... processing annotations GTF
Jul 27 10:09:43 ..... inserting junctions into the genome indices
Jul 27 10:13:32 ... writing Genome to disk ...
Jul 27 10:14:07 ... writing Suffix Array to disk ...
Jul 27 10:18:11 ... writing SAindex to disk
Jul 27 10:18:28 ..... finished successfully
Star genome build result: 0
Mapability result: -1
Ref build result: -1

Now I wanted to start my first IRFinder run and got (using both reference folders) the same error:

Argument error: -r /home/Apps/IRFinder/REF/Mouse-mm10-release81, Does not appear to be a valid IRFinder reference. Could not find /home/Apps/IRFinder/REF/Mouse-mm10-release81/IRFinder/ref-cover.bed

I checked the folder and the file is truly missing. Is there a way to work this out?

Kind regards

**Comment by dg520** [comment]
Hi,

The problem comes from the failure of running mapabillity. Very likely you don't have the permission to call the script. You can use `chmod` to give execute permission to all the script under `bin` and `bin/util`. Please also follow the instruction on Wiki page. Then you need to rebuild the IRFinder reference.

Best,
Dadi

**Comment by OSchwich** [comment]
That really was an easy solution to my issue. 
Thank you, IRFinder is working fine now.

Best
