### ISSUE TITLE
Local annotation

### ISSUE THREAD

**Issue by JLTrincado** [williamritchie/IRFinder#2]
Hi William,

I'm really interested on using the software that you have developed. I'm trying to repdouce the example line that you put on the wiki:

bin/IRFinder -m BuildRef -r REF/Human-hg19-release75 \
-e REF/extra-input-files/RNA.SpikeIn.ERCC.fasta.gz \
-b REF/extra-input-files/Human_hg19_wgEncodeDacMapabilityConsensusExcludable.bed.gz \
-R REF/extra-input-files/Human_hg19_nonPolyA_ROI.bed \
ftp://ftp.ensembl.org/pub/release-75/gtf/homo_sapiens/Homo_sapiens.GRCh37.75.gtf.gz

I'm trying to run this in a cluster. The problem is that this cluster is "closed" to the www and is not able to connect by ftp to the Ensembl website. I was wondering if it would be possible to provide the annotation from a local directory (i tried directly replacing the ftp address by my local directory with the annotaion and it doesn't work).

Thanks a lot and congratulations for your work,
Regards

**Comment by dg520** [comment]
Hi Tricado,

Yes, you can use IRFinder in BuildRefProcess mode via following steps:
1) Download the latest version of IRFinder v1.2.0
2) make a folder where you wanna save the IRFinder reference (should be a clean/new folder)
3) manual downloaded genome fasta file into that folder and rename it to genome.fa (case sensitive)
4) manual downloaded transcriptome gtf file into that folder and rename it to transcripts.gtf (case sensitive)
5) prepare IRFinder reference in BuildRefProcess mode like:
./IRFinder -m BuildRefProcess -r THE_FOLDER_TO_SAVE_REFERENCE -e ... -b ... -R ...

**Comment by OSchwich** [comment]
Hey, 

I am also having issues with the BuildRefProcess using local files. 
Issue is that we don't have a public version of STAR on our cluster, rather we have it locally. 
If I try to start IRFinder it tells me that there is no STAR, I guess I would need to tell IRFinder where to find STAR. 
Is there any possibility to to this?

Best,
Oliver

**Comment by dg520** [comment]
Hi Oliver,

Have you tried -S option? That is supposed to talk the location of STAR executable.

Best,
Dadi
