### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by rjfbiolab** [williamritchie/IRFinder#28]
Hello,

I am interested in using IRFinder, but I seem to have gotten stuck at a very early stage. When I try to install IRFinder on a bioinformatics server, after already loading updated versions of gcc STAR and bedtools, I get an "error 404 page not found" result when following the Wiki instructions to get https://github.com/williamritchie/IRFinder/archive/VERSION.tar.gz 

I am relatively new to github, so I am not sure if I am following the instructions incorrectly or if the link is wrong. 

Thank you!

**Comment by dg520** [comment]
Hi @rjfbiolab ,

`https://github.com/williamritchie/IRFinder/archive/VERSION.tar.gz` is not a real link. The `VERSION` part should be replaced by a real version number when applied to download.

The latest version of IRFinder is v1.2.3, so please run `wget https://github.com/williamritchie/IRFinder/archive/v1.2.3.tar.gz` to download the package.

Best,
Dadi

**Comment by rjfbiolab** [comment]
Hi Dadi,

Thank you! I was able to install it.
