### ISSUE TITLE
IRFinder -m BAM error which reported "Broken pipe" and "Segmentation fault"

### ISSUE THREAD

**Issue by noahpieta** [williamritchie/IRFinder#29]
Hi, Dadi,
I obtain the following errors when trying to run IRFinder in Linux.
i made reference successfully, but when i use the command line:

IRFinder -t 1 -M 1000 -u -m BAM -r bdgp6.88_ref/ -d tf-1 -u ../rong_lab/working/tf-1Aligned.out.bam

it reported an error as below:

IRFinder: line 562: 14920 Broken pipe             gzip -cd "$1"
     14921 Segmentation fault      (core dumped) | "$LIBEXEC/irfinder" "$OUTPUTDIR" "$REF/IRFinder/ref-cover.bed" "$REF/IRFinder/ref-sj.ref" "$REF/IRFinder/ref-read-continues.ref" "$REF/IRFinder/ref-ROI.bed" "$OUTPUTDIR/unsorted.frag.bam" >> "$OUTPUTDIR/irfinder.stdout" 2>> "$OUTPUTDIR/irfinder.stderr"
ERROR: IRFinder appears not to have completed. It appears an unknown component crashed.
ERROR: IRFinder appears not to have completed. It appears an unknown component crashed.
ERROR: IRFinder appears not to have completed. It appears an unknown component crashed.

i found this problem is something like one of the issues but i don't change anything in IRFinder scripts. would you help me to circumvent these errors ?  i'm looking forward your reply.
Thank you very much!
Best
NP

**Comment by dg520** [comment]
Hi NP,

Need some more information from your end. Could you please check the folder `IRFinder` under your IRFinder reference folder and make sure all 8 files inside are not empty? And could you please check the version of your GCC (>4.9.0 required) and bedtools (old versions don't support functions like `complement` and `slop`)? 

BTW, your command itself is correct except you have passed `-u` twice. But that doesn't matter.

Best,
Dadi

**Comment by noahpieta** [comment]
Hi, Dadi,

thank you very much for your reply!

i have checked all 8 files in  IRFinder reference folder/IRFinder are not empty. i think reference is OK. bedtools are the newest version.
my old GCC version is 4.8.5. i have tried to install a local GCC whose version
is 4.9.1 by using conda, as i'm not the root, but the problem is not sovled.
![irfinder_error](https://user-images.githubusercontent.com/9362155/33241808-0e92612c-d306-11e7-94d6-becb13c9cf6c.JPG)
i'm confused if there is anything wrong? 
Thank you again for answer my questions. i'm looking forward your reply.

Best
ZY

**Comment by dg520** [comment]
Hi NP,

I might be wrong, but I think anaconda GCC only links libs under anaconda folder. However IRFinder tries to locate some libraries on the system end directly (not called thru GCC), not inside anaconda. Are you working on a computational cluster where you can load GCC module? Otherwise that might be difficult. Let me know if there are other solutions you can work around the system GCC.

Best,
Dadi

**Comment by noahpieta** [comment]
Hi Dadi,
thank you for your reply!

the answer is yes i'm working on a computational cluster but i'm not the root. 
i'm no sure if i do not misunderstand. i have change my environment to using the system gcc(/usr/bin/gcc), but the version is old. the version and path is as below:
![merk_error](https://user-images.githubusercontent.com/9362155/33308779-d7b80876-d456-11e7-95b6-c4b55757607e.JPG)
does this information help? if more needed, tell me. 

i'm really appreciated to your help!

Best
NP

**Comment by dg520** [comment]
Hi NP,

So the system GCC defaults in 4.8.5. Before we change the default GCC, may I check one more thing please? Are you using an Ensembl GTF when building the reference? If not, could you please check if your GTF file contains the tag `transcript_biotype` and `gene_biotype` or `transcript_type` and `gene_type`? If it didn't have those (stop here and let me know), the built reference lacks some key information and would lead to an error you encountered. 

To change the default GCC, you can follow the [instruction:](https://stackoverflow.com/questions/28970935/osx-replace-gcc-version-4-2-1-with-4-9-installed-via-homebrew) here. Please follow the instruction in the best answer. Try Option 2 and Option 3 (both) he mentioned, that'll change your default system C compiler to your anaconda one. However, I'm not sure if that would cause some other problem or not.

**Comment by abayega** [comment]
Hi Dadi,

thank u for this tool. I am running into this similar error and I realise that it was not resolved here. I have attached my out put. My versions are
gcc (GCC) 5.4.0
STAR-2.6.0c
bedtools v2.27.1

Kindly assist me to determine where this error is coming from. I am working on a cluster

[slurm-823887.txt](https://github.com/williamritchie/IRFinder/files/2813238/slurm-823887.txt)

**Comment by abayega** [comment]
Oh, I already checked that although my gtf is not Ensemble, each gene has 'gene_type' attribute and each transcript and exon has both 'gene_type' and 'transcript_type' tags
