### ISSUE TITLE
Question about the GLM-based analysis with DESeq2

### ISSUE THREAD

**Issue by tommiRa** [williamritchie/IRFinder#33]
Hi,

This is not directly an issue related to the IRFinder itself but rather a question about the example presented in the IRFinder wiki: [https://github.com/williamritchie/IRFinder/wiki/Generalized-Linear-Model-with-Replicates]()

In the example, the final comparison between the Wild type samples and KO samples are made using the following line of code:

`res.diff = results(dds, contrast=list("ConditionXDP.IRFinderIR","ConditionControl.IRFinderIR"))`

However, I can´t see where does ConditionXDP.IRFinderIR and ConditionControl.IRFinderIR come from. As far as I know `resultsNames(dds)` should give us the available options used as contrasts and earlier in the example they have been printed out as :

[1] "Intercept"                   "Condition_KO_vs_WT"

[3] "ConditionWT.IRFinderIR" "ConditionKO.IRFinderIR"

I wonder if I have missed something but I´m quite confused. Could you clarify what happens in this step of the analysis? 

Best wishes,
Tommi

**Comment by dg520** [comment]
Hi Tommi,

Nice catch. The wiki page is a totally wrong copy. I was using IRFinder in another project when writing that example. Thanks for reminding.

Best,
Dadi

**Comment by tommiRa** [comment]
Hi Dadi,

Thanks for your quick response. I kind of thought this might have happened. Now everything makes sense. Many thanks for this nice tool.

Best,
Tommi
