### ISSUE TITLE
IRBase error

### ISSUE THREAD

**Issue by dsanleo** [williamritchie/IRFinder#37]
I tried to access to IRBase (http://mimirna.centenary.org.au/irfinder/database/) during the last days but always I have a connection error. Is there a problem with the server?
And other question, is it possible extract from IRBase the information for a single gene but for all of experiments you already analyzed?
Thanks!
David

**Comment by dg520** [comment]
Hi @dsanleo,

The error is caused by lacking of disk space on the IRBase server. The administrator of the server has left the institute and we're managing to fix the problem ASAP. Sorry for the inconvenience.

Best,
Dadi
