### ISSUE TITLE
component crash

### ISSUE THREAD

**Issue by poflawless** [williamritchie/IRFinder#42]
While I used the lastest  IRFinder-master-1.2.4 version build the reference genome, component crash issues occurred. Although I tried to rebuild the genome and transcripts.gtf , it didn't work as well.  

The issues are:

[gaojingjian@localhost Intron_retaining]$ /home/others/tools/tools/IRFinder-master/bin/IRFinder -r /home/others/chicken/Intron_retaining/gga5ref -d brain   /home/others/chicken/data/brain_1.fq /home/others/chicken/data/brain_2.fq
/home/others/tools/tools/IRFinder-master/bin/IRFinder: line 562: 29452 Broken pipe             "$STAREXEC" --genomeLoad $STARMEMORYMODE --runThreadN $THREADS --genomeDir "$REF/STAR" --outFilterMultimapNmax 1 --outSAMstrandField intronMotif --outFileNamePrefix "${OUTPUTDIR}/" --outSAMunmapped None --outSAMmode NoQS --outSAMtype BAM Unsorted --outStd BAM_Unsorted --readFilesIn "$FIFO1" "$FIFO2"
     29453                       | tee "$OUTPUTDIR/Unsorted.bam"
     29454                       | gzip -cd
     29455 Aborted                 (core dumped) | "$LIBEXEC/irfinder" "$OUTPUTDIR" "$REF/IRFinder/ref-cover.bed" "$REF/IRFinder/ref-sj.ref" "$REF/IRFinder/ref-read-continues.ref" "$REF/IRFinder/ref-ROI.bed" "$OUTPUTDIR/unsorted.frag.bam" >> "$OUTPUTDIR/irfinder.stdout" 2>> "$OUTPUTDIR/irfinder.stderr"
ERROR: IRFinder appears not to have completed. It appears an unknown component crashed.
ERROR: IRFinder appears not to have completed. It appears an unknown component crashed.
ERROR: IRFinder appears not to have completed. It appears an unknown component crashed.
WARN: ERROR: The paired-end trimming routine appeared not to have completed. It may have crashed if there was corruption in the input fastq files. Do the input fastq files have the same number of lines?

While I checked the paired fastq files, they do have the same number of lines.

The commands I used for building indexes for references were:
 /home/others/tools/tools/IRFinder-1.2.3/bin/IRFinder -m BuildRefProcess -r /home/others/chicken/Intron_retaining/gga5ref  -t  25   -s LoadAndKeep

Launching reference build process. The full build should take at least one hour.
Usage : /home/gaojingjian/lindeng/others/tools/tools/IRFinder-1.2.3/bin/util/IRFinder-BuildRefFromEnsembl mode threads STAR-executable ba not exist) additional_genome_reference(eg: ERCC) non_polyA_genes-as-bed region_blacklist-as-bed
Usage example: /home/gaojingjian/lindeng/others/tools/tools/IRFinder-1.2.3/bin/util/IRFinder-BuildRefFromEnsembl BuildRef 12 STAR "ftp://" "IRFinder/REF/Human" "Refernce-ERCC.fa.gz" [non_polyA_genes.bed] [blacklist.bed]
Jun 13 10:21:14 ..... started STAR run
Jun 13 10:21:14 ... starting to generate Genome files
Jun 13 10:21:42 ... starting to sort Suffix Array. This may take a long time...
Jun 13 10:21:49 ... sorting Suffix Array chunks and saving them to disk...
Jun 13 10:25:30 ... loading chunks from disk, packing SA...
Jun 13 10:26:00 ... finished generating suffix array
Jun 13 10:26:00 ... generating Suffix Array index
Jun 13 10:29:08 ... completed Suffix Array index
Jun 13 10:29:08 ..... processing annotations GTF
Jun 13 10:29:11 ..... inserting junctions into the genome indices
Jun 13 10:31:08 ... writing Genome to disk ...
Jun 13 10:31:09 ... writing Suffix Array to disk ...
Jun 13 10:31:15 ... writing SAindex to disk
Jun 13 10:31:18 ..... finished successfully
Star genome build result: 0
Commence STAR mapping run for mapability.
Wed Jun 13 10:31:18 EDT 2018

real	14m7.156s
user	72m44.362s
sys	14m22.213s
Completed STAR run.
Wed Jun 13 10:45:25 EDT 2018
Commence Coverage calculation.

real	1m52.442s
user	23m41.133s
sys	3m38.463s

real	0m0.316s
user	0m0.317s
sys	0m0.012s
Completed coverage exclusion calculation.
Wed Jun 13 10:47:18 EDT 2018
Mapability result: 0
Build Ref 1
Build Ref 2
Build Ref 3
Build Ref 4
Build Ref 5
Build Ref 6
Build Ref 7
Build Ref 8
Build Ref 9
Build Ref 10
Build Ref 11
Build Ref 12
Build Ref 13c
Build Ref 14c
Build Ref 16 - COMPLETE
Ref build result: 0
ALL DONE

**Comment by dg520** [comment]
Hi @poflawless,

Please first check the files in the genome reference folder. Is there any empty file under `IRFinder` subfolder? And which version of GCC and Bedtools are you currently running?

Best,
Dadi

**Comment by poflawless** [comment]
yes，I already found the issues made by the match degree between genome and the transcript.gtf , thanks!
