### ISSUE TITLE
Can I use different aligner instead of STAR ?

### ISSUE THREAD

**Issue by kaanokay** [williamritchie/IRFinder#66]
Hi,

I want use other aligner called HISAT2 in order to perform aligment step. Is this problem for downstream analysis of IRFinder?

Thanks for this nice tool !
Regards,

**Comment by dg520** [comment]
Hi @kaanokay ,

IRFinder uses STAR to calculate the genome mapability during intron reference preparation. 
IRFinder uses STAR to map FASTQ reads to the transcriptome during the quantification stage.

If you already built the intron reference using STAR, IRFinder can do the quantify stage using BAM files generated by other aligners. The BAM should be in a standard BAM format and it has to be sorted by name, not coordinate.

If you want to build a specific IRFinder version purely using your own aligner, you are free to tweak the source code. Keep reading if that's the way your want to go, but other than the information below, you have to be on your own.

The STAR executions involved in IRFinder are independent chunks in the source code. You can replace them with the aligner you like, with similar parameters of you new aligner to those used in STAR call. I listed below where those chunks are:

`bin/util/IRFinder-BuildRefFromEnsembl`:
line 183-199. Change this to how your aligner prepare reference

`bin/util/Mapability`: 
line 29-35. Change this to how you use your aligner to align reads from fasta input

`bin/IRFinder`: 
line 61. Change this to where you aligner program locates. 
line 62. Delete it. It's a STAR-specific parameter
line 204-208. Delete it. It's a STAR-specific version check.
line 458-464,  475-481, 503-509 and 520-526. Change each of these chunks to how your aligner maps read to transcriptome.

After these changes, it should put you in a good shape. But you might have to do a bit further debug. As I said, sorry you're on your own in that case.

Best,
Dadi

**Comment by kaanokay** [comment]
Thanks your quick reply. I will try them to integrate with HISAT2.

**Comment by dg520** [comment]
No promblem
