### ISSUE TITLE
the meaning of "anti-over, anti-near, clean, known exon" in the output file

### ISSUE THREAD

**Issue by genemine** [williamritchie/IRFinder#69]
Hi there,
 In the IRFinder output file, the introns are annotated with tags including anti-over, anti-near, clean, known exon. Can you please help explain what they mean exactly? Thanks.

**Comment by dg520** [comment]
Hi @genemine ,

Each of these terms refers to whether an intronic region is a pure intron or if the region is overlapped with other features in the GTF annotation. You can check the script `bin/util/IntronExclusion.pl` in your IRFinder folder for the detailed definition of these terms if you are familiar. I listed a brief description below:    
`clean`: a pure intron in the annotation    
`known-exon`: the intronic region is contained by an annotated exon    
`anti-over`: the intronic region overlaps with a gene on the antisense strand    
`anti-near`: the intronic region has a nearby gene on the antisense strand, where 'nearby' means within 5000bp upstream and 1000bp downstream.

Best,
Dadi
