### ISSUE TITLE
tophat

### ISSUE THREAD

**Issue by lmanchon** [williamritchie/IRFinder#7]
--Hi,

is it possible to use bam output from tophat or other aligner than STAR?

thank you --

**Comment by dg520** [comment]
Hi @lmanchon,

Yes, IRFinder can be run in the BAM mode which takes BAM file as an input. IRFinder will re-align BAMs via STAR and get junction depth information. 
IRFinder 1.2.0 has just been released, which fixes some major bugs in the original version, and function upgrade as well. I highly recommend to use the latest version.
Please also read the Wiki page about how to prepare a IRFinder reference (including STAR reference). And check the usage for BAM mode: 
`IRFinder -m BAM ......`

Best,
Dadi

**Comment by lmanchon** [comment]
ok thank you so much.
sorry just another question or request:

is there a way to get the intron retention motif or add a column in IRFinder-IR-nondir.txt file to display the motif found ?

thank you,
Laurent --

**Comment by dg520** [comment]
Hi Laurent,

I agree motif analysis is useful and not much has been done in terms of IR. Although IRFinder is currently a quantitative tool, motif analysis can be done by passing information from IR result files to motif tools like MEME. E.g. we can define a "solid" IR cutoff first and then pull out sequences of "solid" IR and non-IR using coordinate information from IRFinder results. 

Best,
Dadi

**Comment by lmanchon** [comment]
ok;
from where can i get coordinate information from IRFinder results to then use them in MEME ?

best,
laurent --

**Comment by dg520** [comment]
Hi Laurent,

If you had applied IRFinder on your samples, you would finder either `IRFindier-IR-dir` or `IRFindier-IR-nondir` under each of your output folder, depending on the directionality of your RNA-seq libraries. Each line of this file contains information of an intron, including its coordinate. You can refer to the session "What are the files in the output folder?" and "What do the columns in the main output files mean?" on Wiki page for more details.


Best,
Dadi

**Comment by lmanchon** [comment]
yes, the file include the coordinates of the introns, but not the coordinates of the intron's motif match, so it is only possible to retrieve the sequence of the intron and it's not easy to discover DNA motifs that could act as IR enhancers or inhibitors.

**Comment by dg520** [comment]
Hi Laurent,

Sorry for misunderstanding. The purpose of IRFinder is to precisely quantify (and compare) IR in each sample. Motif discovery is an important downstream analysis, however it's not the original purpose of IRFinder. And IRFinder cannot suggest suspicious to be enhancers/silencer. Agree that's an area worthy to explore. It has to be done in another approach. Here are some tools I found useful:

http://hollywood.mit.edu/acescan2/index.html
http://www.umd.be/HSF3/HSF.shtml
http://regrna.mbc.nctu.edu.tw/html/prediction.html

Best,
Dadi

**Comment by lmanchon** [comment]
no worries.
Thank you so much for the links and those tools to explore.
best,
laurent --
