### ISSUE TITLE
IRFinder/bin/util/Build-BED-refs.sh: line 186: [: missing `]'

### ISSUE THREAD

**Issue by chichaochen** [williamritchie/IRFinder#72]
error message:
IRFinder/bin/util/Build-BED-refs.sh: line 186: [: missing `]'

**Comment by dg520** [comment]
Hi @chichaochen ,

You are right. I missed a space before `]` on that line. I've just released an update. Please download the new v1.2.6, and let me know if you encountered any other issue. Sorry for the inconvenience. 

Best,
Dadi

**Comment by chichaochen** [comment]
Thanks. Like irfinder and use a lot!

**Comment by dg520** [comment]
@chichaochen Glad to hear that. Thanks for supporting us.

**Comment by chichaochen** [comment]
Can i confirm one thing with you?
If i git clone the newest version, i don't need to 'make', right?

Thanks
Chichao

**Comment by dg520** [comment]
In most case you don't need to `make`. Only do `make` when the quantification step encounters C error. Please refer to [this page](https://github.com/williamritchie/IRFinder/wiki/Troubleshoot#issue-2-broken-pipe---gzip--cd-1-xxxxx-segmentation-fault-or-error-irfinder-appears-not-to-have-completed-it-appears-an-unknown-component-crashed) for more details.

**Comment by chichaochen** [comment]
Thanks! Could you also update the conda irfinder?

**Comment by dg520** [comment]
IRFinder is not a python project, so there is no conda version of it officially.
