### ISSUE TITLE
ReadBlockProcessor error

### ISSUE THREAD

**Issue by andrea-ag** [williamritchie/IRFinder#77]
Hi,
I'm trying to install the last version of IRFinder, but I get the ReadBlockProcessor error as described in the installing page. However, all requirements seem to be satisfied.

IRFINDER: IRFinder-1.2.6_hotfix_R_bug
OS: Ubuntu 18.04.4 LTS
GCC: 7.4.0
GLIBC: 2.27
perl: 5.0
STAR: 2.7.3a
bedtools: v2.29.2
command: make
error: ReadBlockProcessor_CoverageBlocks.cpp:234:9: error: ‘NAN’ was not declared in this scope

Any suggestions?
Thank you a lot,
Andrea

**Comment by dg520** [comment]
Hi @andrea-ag ,

Seems Ubuntu GCC does not link the cmath library automatically. Could you please insert a new line of `#include <cmath>` on top of either `ReadBlockProcessor_CoverageBlocks.h` or `ReadBlockProcessor_CoverageBlocks.cpp` with other `#Iinclude`'s? Then you should be able to compile. Let me know if the problem persists. 

Best,
Dadi

**Comment by dg520** [comment]
Hi @andrea-ag ,

When re-compiling, make sure you've run `make clean first`:
```

**Comment by andrea-ag** [comment]
Hi Dadi,
adding #include <cmath> on top of ReadBlockProcessor_CoverageBlocks.h solved the issue. The tool now works.
Thank you a lot for your fast help and reply,
Andrea

**Comment by dg520** [comment]
Hi @andrea-ag ,
Thanks for reporting the issue and glad to know things work out. I'm closing the issue now. If you have further questions of the same issue, feel free to re-open it.

Best,
Dadi
