### ISSUE TITLE
Buffer size is too small for some BAM headers

### ISSUE THREAD

**Issue by ckmah** [williamritchie/IRFinder#79]
I recently ran IRFinder on some TCGA samples only to find that the buffer size was too small and caused the program to crash. Any chance of increasing it? Simple hack that worked for me was increasing it by a factor of 8. Tried multiplying size by 4 but that was too small. Here are the lines in question:

https://github.com/williamritchie/IRFinder/blob/9e51bb261724051f484e84710e8ebebd36f2a7de/src/irfinder/ReadBlockProcessor_OutputBAM.h#L64-L65

Thanks!

**Comment by dg520** [comment]
Hi @ckmah ,

For me to better understand this problem, could you please show me the full standard error when IRFinder crashed? I'm not sure why this could caused by buffer size.

Best,
Dadi

**Comment by dg520** [comment]
Hi @ckmah ,

You're totally right. By solving another user's problem, I realize for some genome with a lot of scaffolds this will not be sufficient. Thanks for pointing this out and apologize I didn't get it at beginning. This module to generate another BAM in addition to the STAR alignment might be redundant. I'll think if I should remove it or fix the buffer size in the next release.

BTW, if the genome has too many scaffolds, the reference preparation would be influenced as well. The IRFinder might not create complete reference using the current one-shot-`awk`-based approach, which is another problem. A potential solution is to process the genome scaffold by scaffold.

Best,
Dadi
