### ISSUE TITLE
Disable unsorted output

### ISSUE THREAD

**Issue by jthomas5062** [williamritchie/IRFinder#8]
I'm trying to disable the generation of the unsorted BAM output file, as my input file is already unsorted.

The man page gives this option: 
-u. Unsorted output. Do not sort the read fragment BAM file. Default is to sort if a novosort license is present.

Here's my current invocation:

IRFinder \
-m BAM \
-r /IRFinder/hg19/Human-hg19-release75 \
-t 8 \
-u \
-d ./test_irfinder \
./samples/sample.Aligned.out.bam

I've also tried to pass: -u.

Any thoughts?

Thanks!

**Comment by dg520** [comment]
Hi @jthomas5062,

The current IRFinder requires junction counts from STAR. So it re-aligns your BAM input via STAR and generates the Unsorted.bam by default. I suggest to add a line to remove the Unsorted.bam after each run of IRFinder. 

Best,
Dadi

**Comment by jthomas5062** [comment]
Hey,

Makes sense, but my bam file was generated from my own use of STAR. Maybe some paths aren't explicitly specified. . . 

That said, I've been using an extra line to remove the unsorted.bam so that has been helping!

Thanks :)
James

**Comment by dg520** [comment]
Hi @jthomas5062,

Thanks for using IRFinder. I'm closing this thread. Don't hesitate to open another discussion. 

Best,
Dadi
