### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by qicaibiology** [williamritchie/IRFinder#81]
> $ wget https://github.com/williamritchie/IRFinder/archive/v1.2.6.tar.gz
> --2020-04-14 14:28:20--  https://github.com/williamritchie/IRFinder/archive/v1.2.6.tar.gz
> Resolving github.com (github.com)... 140.82.113.4
> Connecting to github.com (github.com)|140.82.113.4|:443... connected.
> HTTP request sent, awaiting response... 302 Found
> Location: https://codeload.github.com/williamritchie/IRFinder/tar.gz/v1.2.6 [following]
> --2020-04-14 14:28:20--  https://codeload.github.com/williamritchie/IRFinder/tar.gz/v1.2.6
> Resolving codeload.github.com (codeload.github.com)... 140.82.114.9
> Connecting to codeload.github.com (codeload.github.com)|140.82.114.9|:443... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2020-04-14 14:28:20 ERROR 404: Not Found.

Does anyone has the same issue?

**Comment by dg520** [comment]
Hi @qicaibiology ,

Please try this: 
```
wget https://github.com/williamritchie/IRFinder/archive/v1.2.6_hotfix_R_bug.tar.gz
```

Best,
Dadi

**Comment by qicaibiology** [comment]
> Hi @qicaibiology ,
> 
> Please try this:
> 
> ```
> wget https://github.com/williamritchie/IRFinder/archive/v1.2.6_hotfix_R_bug.tar.gz
> ```
> 
> Best,
> Dadi

Thanks, I used conda to install yesterday instead.

**Comment by dg520** [comment]
Hi @qicaibiology ,
The conda repository is automatically generated by Conda team. I'm not sure if it's referred to the latest IRFinder or not. There is a bug in the original release of IRFinder v1.2.6. That release is discrepant now, that is why your `wget` failed. I highly encourage your to use I link I gave above to avoid future error. 

Best,
Dadi

**Comment by qicaibiology** [comment]
> Hi @qicaibiology ,
> The conda repository is automatically generated by Conda team. I'm not sure if it's referred to the latest IRFinder or not. There is a bug in the original release of IRFinder v1.2.6. That release is discrepant now, that is why your `wget` failed. I highly encourage your to use I link I gave above to avoid future error.
> 
> Best,
> Dadi

OK. I will take your advice and give it a try

Thank you for prompt reply

Best,
Cai
