### ISSUE TITLE
difficulties in buiding IRfinder reference

### ISSUE THREAD

**Issue by qicaibiology** [williamritchie/IRFinder#82]
Hi:
I used conda to install the IRFinder and run it on the server. What I did is:

> (base) [caiqi@midway2-login2 IRFinder_1]$ module load STAR
> (base) [caiqi@midway2-login2 IRFinder_1]$ module load perl
> (base) [caiqi@midway2-login2 IRFinder_1]$ module load gcc
> (base) [caiqi@midway2-login2 IRFinder_1]$ IRFinder -m BuildRef -r REF/Mouse-mm10-release81 \
> >     -e REF/extra-input-files/RNA.SpikeIn.ERCC.fasta.gz \
> >     -R REF/extra-input-files/Mouse_mm10_nonPolyA_ROI.bed \
> >     ftp://ftp.ensembl.org/pub/release-81/gtf/mus_musculus/Mus_musculus.GRCm38.81.gtf.gz
> Argument error: -e REF/extra-input-files/RNA.SpikeIn.ERCC.fasta.gz. Specified ERCC/extra-reference file does not exist.
> IRFinder version: 1.2.4
> Usage: /home/caiqi/anaconda3/bin/IRFinder -r ReferenceDir raw_reads_1.fastq[.gz] [raw_reads_2.fastq[.gz]]
> Usage: /home/caiqi/anaconda3/bin/IRFinder -m BAM -r ReferenceDir Unsorted.bam
> Usage: /home/caiqi/anaconda3/bin/IRFinder -m BuildRef -r ReferenceDir ftp://ftp.ensembl.org/pub/release-89/gtf/mus_musculus/Mus_musculus.GRCm38.89.gtf.gz

Does anybody has some guide on this?

Also, I want to ask a question on the requirements about running IRFinder: in the beginning, it reads that I need gcc, perl, bedtools, and Glibc. I saw I can do module load gcc, perl, bedtools, STAR. but I can not get Glibc. So my question is what does this requirement mean: does it mean that every time I run IRFinder, I need to do module load?

Appreciate a lot for your answer.

Cai

**Comment by dg520** [comment]
Hi @qicaibiology ,

If possible, please try to download the latest IRFinder from GitHub, not conda repository.  
If you want to test the example command, you have to call it within the IRFinder package folder, as all the paths are relative paths in the command. If you get IRFinder from `conda install`, you have to figure out which directory conda put IRFinder to.

To your requirement questions:
1. GLIBC is supposed to be C++ libraries that comes with your system OS (Linux distro only). You GCC complier should be set to be aware of where these libraries are, and use them to compile C++ codes. In most cases, directly `module load` GLIBC will not be helpful.
2. IRFinder comes with a pre-compliled binary file for you. In most cases, you don't have to load GCC and GLIBC to run IRFinder.  This is only needed when you have to re-compile IRFinder yourself. 
3. If your user environment doesn't include Perl, Bedtools and STAR that meet the requirements of IRFinder, you have to load them everytime before you run IRFinder. An alternative way is to modify your `.bashrc` file, so that they will be loaded automatically when you login to your server. 

Best,
Dadi

**Comment by qicaibiology** [comment]
> Hi @qicaibiology ,
> 
> If possible, please try to download the latest IRFinder from GitHub, not conda repository.
> If you want to test the example command, you have to call it within the IRFinder package folder, as all the paths are relative paths in the command. If you get IRFinder from `conda install`, you have to figure out which directory conda put IRFinder to.
> 
> To your requirement questions:
> 
> 1. GLIBC is supposed to be C++ libraries that comes with your system OS (Linux distro only). You GCC complier should be set to be aware of where these libraries are, and use them to compile C++ codes. In most cases, directly `module load` GLIBC will not be helpful.
> 2. IRFinder comes with a pre-compliled binary file for you. In most cases, you don't have to load GCC and GLIBC to run IRFinder.  This is only needed when you have to re-compile IRFinder yourself.
> 3. If your user environment doesn't include Perl, Bedtools and STAR that meet the requirements of IRFinder, you have to load them everytime before you run IRFinder. An alternative way is to modify your `.bashrc` file, so that they will be loaded automatically when you login to your server.
> 
> Best,
> Dadi

Hi Dadi:
Thanks again for your help. That is very useful for me to learn to use IRFinder.
I did download IRFinder from the link you gave me but still have problems:

> (base) [caiqi@midway2-login2 IRFinder-1.2.6_hotfix_R_bug]$ ls
> LICENSE  README.md  REF  bin  src
> (base) [caiqi@midway2-login2 IRFinder-1.2.6_hotfix_R_bug]$ bin/IRFinder -m BuildRef -r REF/Mouse-mm10-release81 \
> >     -e REF/extra-input-files/RNA.SpikeIn.ERCC.fasta.gz \
> >     -R REF/extra-input-files/Mouse_mm10_nonPolyA_ROI.bed \
> >     ftp://ftp.ensembl.org/pub/release-81/gtf/mus_musculus/Mus_musculus.GRCm38.81.gtf.gz
> Launching reference build process. The full build should take at least one hour.
> Usage : /scratch/midway2/caiqi/IRFinder_1/IRFinder-1.2.6_hotfix_R_bug/bin/util/IRFinder-BuildRefFromEnsembl mode threads STAR-executable base_ftp_url_of_ensembl_genome+gtf output_directory(must not exist) additional_genome_reference(eg: ERCC) non_polyA_genes-as-bed region_blacklist-as-bed
> Usage example: /scratch/midway2/caiqi/IRFinder_1/IRFinder-1.2.6_hotfix_R_bug/bin/util/IRFinder-BuildRefFromEnsembl BuildRef 12 STAR "ftp://ftp.ensembl.org/pub/release-75/fasta/homo_sapiens/dna/" "IRFinder/REF/Human" "Refernce-ERCC.fa.gz" [non_polyA_genes.bed] [blacklist.bed]
> Trying to fetch dna.primary_assembly and GTF based on:
> ftp://ftp.ensembl.org/pub/release-81/gtf/mus_musculus/Mus_musculus.GRCm38.81.gtf.gz
> 
> --2020-04-15 10:45:17--  ftp://ftp.ensembl.org/pub/release-81/fasta/mus_musculus/dna/*.dna.primary_assembly.fa.gz
>            => '.listing'
> Resolving ftp.ensembl.org (ftp.ensembl.org)... 193.62.197.76
> Connecting to ftp.ensembl.org (ftp.ensembl.org)|193.62.197.76|:21... connected.
> Logging in as anonymous ... Logged in!
> ==> SYST ... done.    ==> PWD ... done.
> ==> TYPE I ... done.  ==> CWD (1) /pub/release-81/fasta/mus_musculus/dna ... done.
> ==> PASV ... done.    ==> LIST ... done.
> 
>     [ <=>                                                                                                    ] 18,511      --.-K/s   in 0.1s    
> 
> 2020-04-15 10:45:19 (162 KB/s) - '.listing' saved [18511]
> 
> Removed '.listing'.
> --2020-04-15 10:45:19--  ftp://ftp.ensembl.org/pub/release-81/fasta/mus_musculus/dna/Mus_musculus.GRCm38.dna.primary_assembly.fa.gz
>            => 'Mus_musculus.GRCm38.dna.primary_assembly.fa.gz'
> ==> CWD not required.
> ==> PASV ... done.    ==> RETR Mus_musculus.GRCm38.dna.primary_assembly.fa.gz ... done.
> Length: 805987949 (769M)
> 
> 100%[=======================================================================================================>] 805,987,949 17.5MB/s   in 40s    
> 
> 2020-04-15 10:45:59 (19.3 MB/s) - 'Mus_musculus.GRCm38.dna.primary_assembly.fa.gz' saved [805987949]
> 
> --2020-04-15 10:45:59--  ftp://ftp.ensembl.org/pub/release-81/gtf/mus_musculus/Mus_musculus.GRCm38.81.gtf.gz
>            => 'Mus_musculus.GRCm38.81.gtf.gz'
> Resolving ftp.ensembl.org (ftp.ensembl.org)... 193.62.197.76
> Connecting to ftp.ensembl.org (ftp.ensembl.org)|193.62.197.76|:21... connected.
> Logging in as anonymous ... Logged in!
> ==> SYST ... done.    ==> PWD ... done.
> ==> TYPE I ... done.  ==> CWD (1) /pub/release-81/gtf/mus_musculus ... done.
> ==> SIZE Mus_musculus.GRCm38.81.gtf.gz ... 27787599
> ==> PASV ... done.    ==> RETR Mus_musculus.GRCm38.81.gtf.gz ... done.
> Length: 27787599 (26M) (unauthoritative)
> 
> 100%[=======================================================================================================>] 27,787,599  12.1MB/s   in 2.2s   
> 
> 2020-04-15 10:46:03 (12.1 MB/s) - 'Mus_musculus.GRCm38.81.gtf.gz' saved [27787599]
> 
> 
> Apr 15 10:47:05 ..... started STAR run
> Apr 15 10:47:05 ... starting to generate Genome files
> Apr 15 10:48:16 ... starting to sort Suffix Array. This may take a long time...
> Apr 15 10:48:34 ... sorting Suffix Array chunks and saving them to disk...
> Connection to midway2.rcc.uchicago.edu closed by remote host.
> Connection to midway2.rcc.uchicago.edu closed.
> 
I guessed it is memory problem, so i log in again
[caiqi@midway2-login2 IRFinder-1.2.6_hotfix_R_bug]$ ls
LICENSE  README.md  REF  bin  src
[caiqi@midway2-login2 IRFinder-1.2.6_hotfix_R_bug]$ moudule load STAR
-bash: moudule: command not found
[caiqi@midway2-login2 IRFinder-1.2.6_hotfix_R_bug]$ module load STAR
[caiqi@midway2-login2 IRFinder-1.2.6_hotfix_R_bug]$ module load perl
[caiqi@midway2-login2 IRFinder-1.2.6_hotfix_R_bug]$ module load bedtools
[caiqi@midway2-login2 IRFinder-1.2.6_hotfix_R_bug]$ module load gcc

> [caiqi@midway2-login2 IRFinder-1.2.6_hotfix_R_bug]$ srun -c 16 --mem-per-cpu=4096M -n 1 -N 1 -p bigmem2 bin/IRFinder -m BuildRef -r REF/Mouse-mm10-release81 \
> >     -e REF/extra-input-files/RNA.SpikeIn.ERCC.fasta.gz \
> >     -R REF/extra-input-files/Mouse_mm10_nonPolyA_ROI.bed \
> >     ftp://ftp.ensembl.org/pub/release-81/gtf/mus_musculus/Mus_musculus.GRCm38.81.gtf.gz
> Argument error: -r REF/Mouse-mm10-release81. Reference directory must not exist, BuildRef will create it.
> IRFinder version: 1.2.6
> Usage: bin/IRFinder -r ReferenceDir raw_reads_1.fastq[.gz] [raw_reads_2.fastq[.gz]]
> Usage: bin/IRFinder -m BAM -r ReferenceDir Unsorted.bam
> Usage: bin/IRFinder -m BuildRef -r ReferenceDir ftp://ftp.ensembl.org/pub/release-89/gtf/mus_musculus/Mus_musculus.GRCm38.89.gtf.gz
> 
>     -v Show version number of current IRFinder.
>     -m RunMode. FastQ (default), BAM, BuildRef,
>              BuildRefDownload (performs phase 1 of BuildRef only, requires Internet),
>              BuildRefProcess (performs phase 2 of BuildRef only).
> 
> Parameters for BuildRef mode:
>   required:
>     ftp://... A base Ensembl URL to a (gzipped) gtf file
>     -r ReferenceDir. Directory should not yet exist, will be created.
>   optional:
>     -e ExtraGenomeRef.fasta.gz: Typically an ERCC reference.
>     -b Blacklist.bed.gz: BED of regions to be excluded from analysis.
>     -R ROI.bed.gz: A non-overlapping BED file of additional Regions of Interest for read counts.
> 
> Parameters for BuildRefProcess mode:
>   required:
>     -r ReferenceDir. Directory should already contain EXACT files named 'genome.fa' and 'transcripts.gtf' (case-sensitive) for genome and transcriptome annotations respectively.
>   optional:
>     -e ExtraGenomeRef.fasta.gz: Typically an ERCC reference.
>     -b Blacklist.bed.gz: BED of regions to be excluded from analysis.
>     -R ROI.bed.gz: A non-overlapping BED file of additional Regions of Interest for read counts.
> 
> Parameters for FastQ / BAM mode:
>   required:
>     raw_reads_1.fastq.gz: Either single or paired end fastq file.
>     Unsorted.bam: Mapped output, with pairs as sequential records. Paired end must not be coordinate sorted.
>     -r ReferenceDir. As built by the 'BuildRef' option.
>   optional:
>     -a Adaptor sequence. 'none' to disable. Default: Illumina Universal is trimmed.
>     -t Threads. Default is the number of physical CPUs
>     -d Output Directory. Default is the current directory.
>     -s STAR memory mode. NoSharedMemory (default), LoadAndKeep, LoadAndRemove.
>     -S STAR executable. Default is 'STAR'.
>     -u Unsorted output. Do not sort the read fragment BAM file. Default is to sort if
>        a novosort license is present.
>     -M Sort memory. Maximum memory to use for sort, in MB. Default, auto-detected no greater than 10,000MB.
> srun: error: midway2-bigmem01: task 0: Exited with exit code 1

(I also noticed that after I tried it second time my conda environment is killed. Even I use conda activate it can not be waked up.)

Cai

**Comment by qicaibiology** [comment]
> > Hi @qicaibiology ,
> > If possible, please try to download the latest IRFinder from GitHub, not conda repository.
> > If you want to test the example command, you have to call it within the IRFinder package folder, as all the paths are relative paths in the command. If you get IRFinder from `conda install`, you have to figure out which directory conda put IRFinder to.
> > To your requirement questions:
> > 
> > 1. GLIBC is supposed to be C++ libraries that comes with your system OS (Linux distro only). You GCC complier should be set to be aware of where these libraries are, and use them to compile C++ codes. In most cases, directly `module load` GLIBC will not be helpful.
> > 2. IRFinder comes with a pre-compliled binary file for you. In most cases, you don't have to load GCC and GLIBC to run IRFinder.  This is only needed when you have to re-compile IRFinder yourself.
> > 3. If your user environment doesn't include Perl, Bedtools and STAR that meet the requirements of IRFinder, you have to load them everytime before you run IRFinder. An alternative way is to modify your `.bashrc` file, so that they will be loaded automatically when you login to your server.
> > 
> > Best,
> > Dadi
> 
> Hi Dadi:
> Thanks again for your help. That is very useful for me to learn to use IRFinder.
> I did download IRFinder from the link you gave me but still have problems:
> 
> > (base) [caiqi@midway2-login2 IRFinder-1.2.6_hotfix_R_bug]$ ls
> > LICENSE  README.md  REF  bin  src
> > (base) [caiqi@midway2-login2 IRFinder-1.2.6_hotfix_R_bug]$ bin/IRFinder -m BuildRef -r REF/Mouse-mm10-release81 \
> > > ```
> > > -e REF/extra-input-files/RNA.SpikeIn.ERCC.fasta.gz \
> > > -R REF/extra-input-files/Mouse_mm10_nonPolyA_ROI.bed \
> > > ftp://ftp.ensembl.org/pub/release-81/gtf/mus_musculus/Mus_musculus.GRCm38.81.gtf.gz
> > > ```
> > 
> > 
> > Launching reference build process. The full build should take at least one hour.
> > Usage : /scratch/midway2/caiqi/IRFinder_1/IRFinder-1.2.6_hotfix_R_bug/bin/util/IRFinder-BuildRefFromEnsembl mode threads STAR-executable base_ftp_url_of_ensembl_genome+gtf output_directory(must not exist) additional_genome_reference(eg: ERCC) non_polyA_genes-as-bed region_blacklist-as-bed
> > Usage example: /scratch/midway2/caiqi/IRFinder_1/IRFinder-1.2.6_hotfix_R_bug/bin/util/IRFinder-BuildRefFromEnsembl BuildRef 12 STAR "ftp://ftp.ensembl.org/pub/release-75/fasta/homo_sapiens/dna/" "IRFinder/REF/Human" "Refernce-ERCC.fa.gz" [non_polyA_genes.bed] [blacklist.bed]
> > Trying to fetch dna.primary_assembly and GTF based on:
> > ftp://ftp.ensembl.org/pub/release-81/gtf/mus_musculus/Mus_musculus.GRCm38.81.gtf.gz
> > --2020-04-15 10:45:17--  ftp://ftp.ensembl.org/pub/release-81/fasta/mus_musculus/dna/*.dna.primary_assembly.fa.gz
> > => '.listing'
> > Resolving ftp.ensembl.org (ftp.ensembl.org)... 193.62.197.76
> > Connecting to ftp.ensembl.org (ftp.ensembl.org)|193.62.197.76|:21... connected.
> > Logging in as anonymous ... Logged in!
> > ==> SYST ... done.    ==> PWD ... done.
> > ==> TYPE I ... done.  ==> CWD (1) /pub/release-81/fasta/mus_musculus/dna ... done.
> > ==> PASV ... done.    ==> LIST ... done.
> > ```
> > [ <=>                                                                                                    ] 18,511      --.-K/s   in 0.1s    
> > ```
> > 
> > 
> > 2020-04-15 10:45:19 (162 KB/s) - '.listing' saved [18511]
> > Removed '.listing'.
> > --2020-04-15 10:45:19--  ftp://ftp.ensembl.org/pub/release-81/fasta/mus_musculus/dna/Mus_musculus.GRCm38.dna.primary_assembly.fa.gz
> > => 'Mus_musculus.GRCm38.dna.primary_assembly.fa.gz'
> > ==> CWD not required.
> > ==> PASV ... done.    ==> RETR Mus_musculus.GRCm38.dna.primary_assembly.fa.gz ... done.
> > Length: 805987949 (769M)
> > 100%[=======================================================================================================>] 805,987,949 17.5MB/s   in 40s
> > 2020-04-15 10:45:59 (19.3 MB/s) - 'Mus_musculus.GRCm38.dna.primary_assembly.fa.gz' saved [805987949]
> > --2020-04-15 10:45:59--  ftp://ftp.ensembl.org/pub/release-81/gtf/mus_musculus/Mus_musculus.GRCm38.81.gtf.gz
> > => 'Mus_musculus.GRCm38.81.gtf.gz'
> > Resolving ftp.ensembl.org (ftp.ensembl.org)... 193.62.197.76
> > Connecting to ftp.ensembl.org (ftp.ensembl.org)|193.62.197.76|:21... connected.
> > Logging in as anonymous ... Logged in!
> > ==> SYST ... done.    ==> PWD ... done.
> > ==> TYPE I ... done.  ==> CWD (1) /pub/release-81/gtf/mus_musculus ... done.
> > ==> SIZE Mus_musculus.GRCm38.81.gtf.gz ... 27787599
> > ==> PASV ... done.    ==> RETR Mus_musculus.GRCm38.81.gtf.gz ... done.
> > Length: 27787599 (26M) (unauthoritative)
> > 100%[=======================================================================================================>] 27,787,599  12.1MB/s   in 2.2s
> > 2020-04-15 10:46:03 (12.1 MB/s) - 'Mus_musculus.GRCm38.81.gtf.gz' saved [27787599]
> > Apr 15 10:47:05 ..... started STAR run
> > Apr 15 10:47:05 ... starting to generate Genome files
> > Apr 15 10:48:16 ... starting to sort Suffix Array. This may take a long time...
> > Apr 15 10:48:34 ... sorting Suffix Array chunks and saving them to disk...
> > Connection to midway2.rcc.uchicago.edu closed by remote host.
> > Connection to midway2.rcc.uchicago.edu closed.
> 
> I guessed it is memory problem, so i log in again
> [caiqi@midway2-login2 IRFinder-1.2.6_hotfix_R_bug]$ ls
> LICENSE README.md REF bin src
> [caiqi@midway2-login2 IRFinder-1.2.6_hotfix_R_bug]$ moudule load STAR
> -bash: moudule: command not found
> [caiqi@midway2-login2 IRFinder-1.2.6_hotfix_R_bug]$ module load STAR
> [caiqi@midway2-login2 IRFinder-1.2.6_hotfix_R_bug]$ module load perl
> [caiqi@midway2-login2 IRFinder-1.2.6_hotfix_R_bug]$ module load bedtools
> [caiqi@midway2-login2 IRFinder-1.2.6_hotfix_R_bug]$ module load gcc
> 
> > [caiqi@midway2-login2 IRFinder-1.2.6_hotfix_R_bug]$ srun -c 16 --mem-per-cpu=4096M -n 1 -N 1 -p bigmem2 bin/IRFinder -m BuildRef -r REF/Mouse-mm10-release81 \
> > > ```
> > > -e REF/extra-input-files/RNA.SpikeIn.ERCC.fasta.gz \
> > > -R REF/extra-input-files/Mouse_mm10_nonPolyA_ROI.bed \
> > > ftp://ftp.ensembl.org/pub/release-81/gtf/mus_musculus/Mus_musculus.GRCm38.81.gtf.gz
> > > ```
> > 
> > 
> > Argument error: -r REF/Mouse-mm10-release81. Reference directory must not exist, BuildRef will create it.
> > IRFinder version: 1.2.6
> > Usage: bin/IRFinder -r ReferenceDir raw_reads_1.fastq[.gz] [raw_reads_2.fastq[.gz]]
> > Usage: bin/IRFinder -m BAM -r ReferenceDir Unsorted.bam
> > Usage: bin/IRFinder -m BuildRef -r ReferenceDir ftp://ftp.ensembl.org/pub/release-89/gtf/mus_musculus/Mus_musculus.GRCm38.89.gtf.gz
> > ```
> > -v Show version number of current IRFinder.
> > -m RunMode. FastQ (default), BAM, BuildRef,
> >          BuildRefDownload (performs phase 1 of BuildRef only, requires Internet),
> >          BuildRefProcess (performs phase 2 of BuildRef only).
> > ```
> > 
> > 
> > Parameters for BuildRef mode:
> > required:
> > ftp://... A base Ensembl URL to a (gzipped) gtf file
> > -r ReferenceDir. Directory should not yet exist, will be created.
> > optional:
> > -e ExtraGenomeRef.fasta.gz: Typically an ERCC reference.
> > -b Blacklist.bed.gz: BED of regions to be excluded from analysis.
> > -R ROI.bed.gz: A non-overlapping BED file of additional Regions of Interest for read counts.
> > Parameters for BuildRefProcess mode:
> > required:
> > -r ReferenceDir. Directory should already contain EXACT files named 'genome.fa' and 'transcripts.gtf' (case-sensitive) for genome and transcriptome annotations respectively.
> > optional:
> > -e ExtraGenomeRef.fasta.gz: Typically an ERCC reference.
> > -b Blacklist.bed.gz: BED of regions to be excluded from analysis.
> > -R ROI.bed.gz: A non-overlapping BED file of additional Regions of Interest for read counts.
> > Parameters for FastQ / BAM mode:
> > required:
> > raw_reads_1.fastq.gz: Either single or paired end fastq file.
> > Unsorted.bam: Mapped output, with pairs as sequential records. Paired end must not be coordinate sorted.
> > -r ReferenceDir. As built by the 'BuildRef' option.
> > optional:
> > -a Adaptor sequence. 'none' to disable. Default: Illumina Universal is trimmed.
> > -t Threads. Default is the number of physical CPUs
> > -d Output Directory. Default is the current directory.
> > -s STAR memory mode. NoSharedMemory (default), LoadAndKeep, LoadAndRemove.
> > -S STAR executable. Default is 'STAR'.
> > -u Unsorted output. Do not sort the read fragment BAM file. Default is to sort if
> > a novosort license is present.
> > -M Sort memory. Maximum memory to use for sort, in MB. Default, auto-detected no greater than 10,000MB.
> > srun: error: midway2-bigmem01: task 0: Exited with exit code 1
> 
> (I also noticed that after I tried it second time my conda environment is killed. Even I use conda activate it can not be waked up.)
> 
> Cai

Hi Dadi:

I realized that it might be the folder created there. So I deleted the IRFinder file and installed again. It is running now. Hopefully, I will get something. Thank you for your timely help.
Cai

**Comment by dg520** [comment]
Hi @qicaibiology ,

I suggest you allocate at least 32GB memory to build IRFinder reference on the mouse genome, especially when you want to use as many as 16 cores. 
You have to remove the reference folder `REF/Mouse-mm10-release8` before re-run. IRFinder only makes reference in a NEW folder to avoid overwriting existing ones. 
Please read the error message carefully first. 

Best,
Dadi

**Comment by qicaibiology** [comment]
> Hi @qicaibiology ,
> 
> I suggest you allocate at least 32GB memory to build IRFinder reference on the mouse genome, especially when you want to use as many as 16 cores.
> You have to remove the reference folder `REF/Mouse-mm10-release8` before re-run. IRFinder only makes reference in a NEW folder to avoid overwriting existing ones.
> Please read the error message carefully first.
> 
> Best,
> Dadi

OK. Thank you! It is already running.

Best,
Cai

**Comment by qicaibiology** [comment]
> > Hi @qicaibiology ,
> > I suggest you allocate at least 32GB memory to build IRFinder reference on the mouse genome, especially when you want to use as many as 16 cores.
> > You have to remove the reference folder `REF/Mouse-mm10-release8` before re-run. IRFinder only makes reference in a NEW folder to avoid overwriting existing ones.
> > Please read the error message carefully first.
> > Best,
> > Dadi
> 
> OK. Thank you! It is already running.
> 
> Best,
> Cai



> > Hi @qicaibiology ,
> > I suggest you allocate at least 32GB memory to build IRFinder reference on the mouse genome, especially when you want to use as many as 16 cores.
> > You have to remove the reference folder `REF/Mouse-mm10-release8` before re-run. IRFinder only makes reference in a NEW folder to avoid overwriting existing ones.
> > Please read the error message carefully first.
> > Best,
> > Dadi
> 
> OK. Thank you! It is already running.
> 
> Best,
> Cai

Hi Dadi:

Is this a problem of network?

> --2020-04-15 11:50:11--  ftp://ftp.ensembl.org/pub/release-81/fasta/mus_musculus/dna/*.dna.primary_assembly.fa.gz
>   (try: 5) => '.listing'
> Connecting to ftp.ensembl.org (ftp.ensembl.org)|193.62.197.76|:21... failed: Connection timed out.
> Retrying.

Thanks,
Cai

**Comment by dg520** [comment]
I think so. Nothing wrong with the address. I can download that on my end.

**Comment by qicaibiology** [comment]
> I think so. Nothing wrong with the address. I can download that on my end.

I will try to build from locally then. I noticed that in the manual there might be a mistake:

> $ mkdir REF/Human-hg19-release75                                                         #This must be a new/clean folder
> $ ln -s /FULL_PATH/downloads/Homo_sapiens.GRCh37.75.fasta REF/Human-hg19-release75/genome.fa        #File name MUST be "genome.fa". Case-sensitive. FULL PATH of the original file must be given to make link work.
> $ ln -s /FULL_PATH/downloads/Homo_sapiens.GRCh37.75.fasta REF/Human-hg19-release75/transcripts.gtf  #File name MUST be "transcripts.gtf". Case-sensitive. FULL PATH of the original file must be given to make link work. 

The second ln command, maybe it should be "Homo_sapiens.GRCh37.75.gtf"?

Thanks again,

Cai

**Comment by dg520** [comment]
Yes, you're right. Link the GTF file please.

**Comment by qicaibiology** [comment]
> Yes, you're right. Link the GTF file please.

OK. 
Can you tell me what is the command should I type in the manual: -e ... -b ... -R ...
What should I fill for "..." with only genome.fa and gtf file.

Thank you,

Cai

**Comment by dg520** [comment]
These are optional, and you can skip them. Please call `bin/IRFinder` without argument to see the detailed usage.

**Comment by qicaibiology** [comment]
> These are optional, and you can skip them. Please call `bin/IRFinder` without argument to see the detailed usage.
Got it.
Running now. I will close this issue after getting the files needed. Thank you so much.

Cheers,

Cai
