### ISSUE TITLE
transcript_biotype and gene_biotype

### ISSUE THREAD

**Issue by OlgaVT** [williamritchie/IRFinder#86]
Hi,

I wonder, what description ('protein_coding', 'retained-intron', and so on) in those fields - transcript_biotype and gene-biotype - from the gtf annotation file is important for IRFinder to prepare the reference? I am trying to make my custom gtf files and would like to format it properly.

Thank you!

**Comment by dg520** [comment]
Hi @OlgaVT ,

For a GTF file, IRFinder explicitly looks for `gene_name`, `gene_id`, `transcript_id`, `transcript_biotype` and `gene_biotype` in every row marked as exon (the third column).
For a GFF version 2 file, IRFinder explicitly looks for `ID`, `gene_id`, `transcript_id`, `transcript_biotype` and `gene_biotype` in every row marked as exon (the third column).
For a GFF version 3 file, IRFinder explicitly looks for `Name`, `gene_id`, `transcript_id`, `transcript_biotype` and `gene_biotype` in every row marked as exon (the third column).

Let me know how it works for you.

Best,
Dadi

**Comment by OlgaVT** [comment]
Thank you for a very quick reply. Does it look for any particular biotype description, like 'intron retention' or 'protein coding'?

**Comment by dg520** [comment]
Hi @OlgaVT ,
Please put `protein_coding` (note there is an underline in the middle) and/or `processed_transcript`. That's the only two descriptions IRFinder will calculate IR from.

Best,
Dadi

**Comment by OlgaVT** [comment]
Thank you! I will try and let you know.

**Comment by OlgaVT** [comment]
Hi,
thank you very much for your help. It worked. 

I put those categories: gene_name, gene_id, transcript_id, transcript_biotype, and gene_biotype into my gtf file. The only thing, I forgot to do at first - the quotation marks. With these categories and quotation marks (for example, gene_id "ENSG00000162194";) the reference build and quantification went with no problems. Thank you again.
