### ISSUE TITLE
question

### ISSUE THREAD

**Issue by jano15** [williamritchie/IRFinder#9]
in the IRFinder paper there is this sentence: "On pre-aligned sequencing data, our program can run on a desktop computer with less than 2 GB of memory and takes approximately 10 minutes to detect IR events. "

but when i will run the secetion 12 (Then run IRFinder to analyze the experiment:) 
I must first build an index with STAR and that cant i do in 10 minutes with 2GB memory ...

Or exists an extra option to run aligned bam file with a gtf file only..?

**Comment by dg520** [comment]
Hi Jano,

The current IRFinder requires junction counts from STAR. We don't have an option to start from BAM and GTF only. IRFinder is designed to run on a computational node instead of a personal laptop.

Best,
Dadi
